### ISSUE TITLE
Pretty error messages

### ISSUE THREAD

**Issue by rzane** [smooth-code/jest-puppeteer#10]
Have you thought of incorporating `jest-diff` and `jest-matcher-utils` in the `expect-puppeteer` package? It would be nice to have more descriptive and colorful error messages.

I understand the desire to keep `expect-puppeteer` non-jest-specific, but I am fairly certain that those utility packages don't depend on Jest.

For example, it would be nice to see what the `textContent` is on the page when `toMatch` fails.

**Comment by neoziro** [comment]
Thanks for your suggestion, yes it is an improvement that I would like to make. The project is very young but it would be nice.

**Comment by rzane** [comment]
Great! If I have some spare time, maybe I'll work on this.

**Comment by kaufmann42** [comment]
Just would like to throw out there that (consola)[https://github.com/nuxt/consola] is up and coming in this department :) . I will also look into this if I have some time.

**Comment by neoziro** [comment]
Feature created, feel free to take it! #129
