### ISSUE TITLE
Unable to set timeout in launch options

### ISSUE THREAD

**Issue by Dartv** [smooth-code/jest-puppeteer#101]
Setting timeout to 0 or any other value doesn't seem to do anything. I keep getting this error:
```
Navigation Timeout Exceeded: 30000ms exceeded

      at Promise.then (node_modules/puppeteer/lib/NavigatorWatcher.js:73:21)
```
My app is huge and builds around minute or two.
My `jest-puppeteer.config.js`:
```
module.exports = {
  server: {
    command: 'yarn --cwd app start --port 1337',
    launchTimeout: 600000,
    port: 1337,
    debug: true,
  },
  launch: {
    headless: false,
    timeout: 0,
  },
};
```

I also tried setting timeout in `args` and setting `headless` to true but no luck.

**Comment by flyingsky** [comment]
I think the `launch.timeout` is for "Maximum time in milliseconds to wait for the browser instance to start. Defaults to 30000 (30 seconds). Pass 0 to disable timeout." The Navigation timeout is changed by `page.setDefaultNavigationTimeout(timeout)` or the option in `page.waitForNavigation(options)`.

**Comment by Dartv** [comment]
Yes, you're absolutely right. Thanks.
