### ISSUE TITLE
Configure it correctly with enzyme

### ISSUE THREAD

**Issue by deser** [smooth-code/jest-puppeteer#105]
Hi Guys,
I tried to use `jest-puppeteer` with enzyme tests but they fail with the next error: `It looks like you called `mount()` without a global document being loaded.`
So I have next questions:
1. Do I need to do something extra to run my tests in puppeteer with enzyme?
2. Do I need puppeteer at all? Does it replaces running tests via Karma in Chrome? 

Thanks

**Comment by neoziro** [comment]
Hi @deser, Puppeteer is just an API to control a Chrome Headless browser. You are at the place of the user, you can click, drag & drop, type with keyboard, etc... But as a user you are not able to run Enzyme, to do it you have to be in the page, in the JavaScript code of the website.

So the short answer is no, you can't use Puppeteer + Enzyme and it does not replace Karma. This library is designed for E2E testing.

**Comment by guaiamum** [comment]
Hey @deser , did you get any luck with the error? It happened the same to me, as soon as I add `preset: 'jest-puppeteer',` in my jest config, my tests with ezyme throw the same global document error...

**Comment by benbonnet** [comment]
using jest-pupeteer is a no-go for enzyme users then, bottom line ?
