### ISSUE TITLE
How to close express.js correctly 

### ISSUE THREAD

**Issue by gorshkov-leonid** [smooth-code/jest-puppeteer#107]
Hi, I specified following command for `jest-dev-server`:
```
//command.js
const app = express();
let server = app.listen(args.port, () => {
   console.log(`Server listening on port ${args.port}!`)
});
```

But after test finished I see not closed port 
```
$ netstat -ano | grep 8089
TCP    127.0.0.1:63345        127.0.0.1:8089         TIME_WAIT       0
``` 
And next test run  fails with error on on call of `find-process`: 
> `const [portProcess] = await (0, _findProcess2.default)('port', config.port);`  () 

error:
```
console.error node_modules/jest-jasmine2/build/jasmine/Env.js:157
    Unhandled error

  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:158
    Error: stdout maxBuffer exceeded
        at Socket.onChildStdout (child_process.js:328:14)
        at emitOne (events.js:116:13)
        at Socket.emit (events.js:211:7)
        at addChunk (_stream_readable.js:263:12)
        at readableAddChunk (_stream_readable.js:246:13)
        at Socket.Readable.push (_stream_readable.js:208:10)
        at Pipe.onread (net.js:597:20)
```

So I thought that it's need to close expressjs server correctly. But a cannot to handle any precess's events:
```
process.on('SIGINT', () => {  console.log('1');})
process.on('SIGTERM', () => {  console.log('1'); })
process.on('SIGHUP', () => {  console.log('1'');})
process.on('close', () => {  console.log('1');})
process.once('exit', function(){  console.log('1'); })
```

Then I figured out that `spawnd/destroy` is used and it [removes all listeners](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/spawnd/src/index.js#L27)

So, 
1) How can I can ensure expressjs correctly closed? 
2) Why `find-process` failes on checking?

Windows 10, NodeJs 8.11.3, headless: false

**Comment by gorshkov-leonid** [comment]
'netstat -anob'
```
 TCP    [::1]:8089             [::1]:49653            TIME_WAIT       0
 [klnagent.exe]
  TCP    [::1]:49654            [::1]:8089             TIME_WAIT       0
 [klnagent.exe]
 TCP    127.0.0.1:49650        127.0.0.1:8089         TIME_WAIT       0
 [klnagent.exe]
```
I think it is antivirus Kaspersky, I'll check it

**Comment by gorshkov-leonid** [comment]
I found system locks connections for 120s:
https://stackoverflow.com/questions/337115/setting-time-wait-tcp
https://docs.oracle.com/cd/E23095_01/Search.93/ATGSearchAdmin/html/s1207adjustingtcpsettingsforheavyload01.html
Can it be related to how child processes finished?

**Comment by neoziro** [comment]
Hello @gorshkov-leonid, I think it is a problem relative to your system configuration. On mine (macOS High Sierra), a port is released when the process is closed. On your system it seems that the port is retain for a certain amount of time. So it is not related at all with Jest Puppeteer but I let it opened if someone has a solution.

**Comment by neoziro** [comment]
`jest-dev-server` has been created to be able to run a server along your Jest tests. It is common to have to run a server when you write integration tests. Closing express is always complicated but it is not the place to discuss it.
