### ISSUE TITLE
Handle multiple sessions

### ISSUE THREAD

**Issue by flotos** [smooth-code/jest-puppeteer#108]
Hi,
I would like to test the repercussion of an action from a user to another, say for a chat for exemple.
How should i handle that ? I was planning to use multiple puppeteer browser in globalSetup but i've found that in `global.js` browser is a singleton.

Thanks for any help.

**Comment by neoziro** [comment]
Hi @flotos, you can do that using context.

- [Create an incognito browser context](https://github.com/GoogleChrome/puppeteer/blob/v1.7.0/docs/api.md#browsercreateincognitobrowsercontext)
- Create a new page on this context
- Switch between your pages into your test
