### ISSUE TITLE
Use Jest Configuration

### ISSUE THREAD

**Issue by neoziro** [smooth-code/jest-puppeteer#111]
Now that https://github.com/facebook/jest/issues/5957 is merged and release, we can drop `jest-puppeteer.config.js` and use the Jest configuration.

We have to use [`testEnvironmentOptions`](https://jestjs.io/docs/en/configuration#testenvironmentoptions-object) and read configuration from this.

`jest-puppeteer.config.js` support will be deprecated and removed in the next major version.

**Comment by neoziro** [comment]
It is actually not ready because as mentioned in https://github.com/facebook/jest/issues/5957#issuecomment-422027349, it is not possible to access `testEnvironmentOptions` in globalConfig.

**Comment by lukaszfiszer** [comment]
Other projects use `global` for plugin-related config. Example: https://kulshekhar.github.io/ts-jest/user/config/#ts-jest-options jest-puppeteer could easily use this pattern too

**Comment by neoziro** [comment]
Hello @lukaszfiszer, unfortunately `globals` are not accessible in `globalConfig`, see https://github.com/facebook/jest/blob/master/packages/jest-config/src/index.ts#L104. So we are still stuck with `jest-puppeteer.config.js`...
