### ISSUE TITLE
Feature request: match on server output string before running tests

### ISSUE THREAD

**Issue by noinkling** [smooth-code/jest-puppeteer#113]
The server functionality is great, however just because a port is open doesn't necessarily mean a desired page is ready to be navigated to. In my case I'm using Storybook, which listens quickly, but has to wait for a lengthy Webpack compilation step to finish before being usable. To work around this I'm forced to provide big timeout values to `page.goto()` as well as `jest.setTimeout()` if I want to use this functionality.

I was thinking it would be nice if there was an option like `readyPattern` that accepts a regex (and/or string), that could be matched against the child process's stdout stream as a signal to proceed (along with the port detection, if specified). In my case I could specify "webpack built" or "Storybook started", because I know the page will be ready at that point.

```js
// jest-puppeteer.config.js
module.exports = {
  server: {
    command: "yarn run storybook",
    port: 6006,
    readyPattern: /webpack built/
  }
}
```

This is the only way I could think of to hook in to a child process that I don't control the code for, but I think it's an elegant enough solution. Let me know if you think it's a good idea.

**Comment by neoziro** [comment]
Hello @noinkling, I think it is not a very good solution to rely on something displayed in output. I suggest you to use Storybook in production mode, build, then run a server, the webpage will be ready as soon as the port is opened.

**Comment by noinkling** [comment]
The problem with static production builds is that it is even slower, and you still run into the same issue in watch mode - when a file is modified, the tests will try and rerun (and probably timeout) long before the build is ready. With the dev server it's fast after the initial startup, especially because of things like hot reloading.

**Comment by noinkling** [comment]
@neoziro How about just exposing the spawned process? You could simply add an `export` here: https://github.com/smooth-code/jest-puppeteer/blob/89e72b765bd69ea05dd5251f8d155899f13a19c4/packages/jest-dev-server/src/global.js#L41

The other option would be to return it from `setup()`.

This way we'd have the flexibility to implement our own logic, whether it be parsing stdout or waiting on an IPC `message`.

**Comment by neoziro** [comment]
Follow up in #135.

**Comment by BudgieInWA** [comment]
In reply to @noinkling's original question:

> Just because a port is open doesn't necessarily mean a desired page is ready to be navigated to. ... To work around this I'm forced to provide big timeout values to page.goto() as well as jest.setTimeout() if I want to use this functionality.

If all compilation happens before any requests are handled, then you can detect the ready state with `page.goto('http://localhost:8000/', { timeout: 60000 })`. If you can detect the ready state, you can wait on the ready state in `beforeAll`:

```js
beforeAll(async () => {
  await page.goto('http://localhost:8000/', { timeout: 60000 });
});
```

That way, compilation will happen no matter which tests are being run and the long wait time is not attributed to any particular test, so you can still require tests to finish quickly.

**Comment by BudgieInWA** [comment]
In reply to @noinkling's original problem:

> Just because a port is open doesn't necessarily mean a desired page is ready to be navigated to. ... To work around this I'm forced to provide big timeout values to page.goto() as well as jest.setTimeout() if I want to use this functionality.

If all compilation happens before any requests are handled, then you can detect the ready state with `page.goto('http://localhost:8000/', { timeout: 60000 })`. If you can detect the ready state, you can wait on the ready state in `beforeAll`:

```js
beforeAll(async () => {
  await page.goto('http://localhost:8000/', { timeout: 60000 });
});
```

That way, compilation will happen no matter which tests are being run and the long wait time is not attributed to any particular test, so you can still require tests to finish quickly.
