### ISSUE TITLE
is newPage() in environment setup needed?

### ISSUE THREAD

**Issue by hegelstad** [smooth-code/jest-puppeteer#114]
Is there a good reason to open a new page after the browser has opened with a default page already?

https://github.com/smooth-code/jest-puppeteer/blob/1bb21add46cfbccc8054dec11bb47cfe59f6d98f/packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js#L43

**Comment by neoziro** [comment]
Follow up #136
