### ISSUE TITLE
Cannot read property 'removeListener' of undefined

### ISSUE THREAD

**Issue by SophieAu** [smooth-code/jest-puppeteer#116]
Since we updated to version 3.3.0 we are getting the following error when we run `npm test`:

```
TypeError: Cannot read property 'removeListener' of undefined

at PuppeteerEnvironment.teardown 
(node_modules/jest-environment puppeteer/lib/PuppeteerEnvironment.js:109:22) 
at Generator.throw (<anonymous>)
```

Our `jest.config.js` looks like this:
```
module.exports = {
  testMatch: [
	// our test file regex
  ],
  preset: 'jest-puppeteer'
};
```

Weirdly enough, we found a very temporary workaround:
1. remove `"preset": "jest-puppeteer"` from the config and run the tests
-> they fail
2. put it back in, re-run the tests
-> they pass
3. But: run the tests again
-> they fail

The current versions we are using are:
```
"jest": "^23.5.0",
"jest-puppeteer": "^3.3.0",
"puppeteer": "^1.7.0"
```

It did work with the following versions:
```
"jest": "^23.3.0",
"jest-puppeteer": "^3.2.1",
"puppeteer": "^1.6.2"
```

**Comment by SophieAu** [comment]
Version 3.3.1 works like a charm. I just hadn't checked for updates when I created the issue this morning...
Sorry!

**Comment by vivek-kandhvar** [comment]
Using version 3.7.0 and I still see this issue randomly. Anything broken again?

**Comment by xiaoyuhen** [comment]
@vivek-kandhvar 

use jest-puppeteer v3.9 version, If still can't work, Refer to this https://github.com/smooth-code/jest-puppeteer/issues/192#issuecomment-457995612

**Comment by vivek-kandhvar** [comment]
Thanks for the reply. 

I changed my puppeteer version to 1.11.0 and it started working with 3.7.0. Importance of fixing the version in the package.json file!
