### ISSUE TITLE
Chromium background tab cpu/request throttling

### ISSUE THREAD

**Issue by hegelstad** [smooth-code/jest-puppeteer#121]
Hi!

I'd like to report that running Jest tests in parallel might cause some unintended timeouts caused by cpu/request throttling by Chromium. Furthermore, it is totally random because which tab is active in chromium when running parallel tests is random by race condition.

Further explanation of the phenomenon: https://blog.bigbinary.com/2018/08/15/debugging-failing-tests-in-background-tab-in-puppeteer.html

Maybe add this flag to the preset?

**Comment by neoziro** [comment]
Yes of course! PR welcome!

**Comment by neoziro** [comment]
Follow up in #137
