### ISSUE TITLE
Browsers in parallel

### ISSUE THREAD

**Issue by psanlorenzo** [smooth-code/jest-puppeteer#122]
Hi, I need some advices on testing. 
I am using jest with puppeteer to run some tests on a website. When I run them alone they work as intended, but when I try to run them in parallel sometimes all of them pass, sometimes they dont, and I think it may be due to cookies. 

I'd like to know if there is a specific way to run independent browsers or maybe another way to do this.
I'm pretty new as web-developer and only few weeks of experience on testing. 

Excuse my poor english.

**Comment by neoziro** [comment]
@psanlorenzo hi, why closed?

**Comment by psanlorenzo** [comment]
@neoziro I don't think I can solve this easily, and my skills are still pretty low. I ended up testing sequentially.

**Comment by sorodrigo** [comment]
Hello I ran into this issue and found a way to run tests sequentially. This is not documented, I was wondering if maybe we should add it to the readme. I can make a PR with the changes if you agree. @neoziro

**Comment by neoziro** [comment]
@psanlorenzo yes I think we should document it. Or better we can probably set if as default in the preset.

**Comment by sorodrigo** [comment]
if you point me to the right direction I may be able to make pull request.
