### ISSUE TITLE
How to get jest-puppeteer.config.js to work with create-react-app

### ISSUE THREAD

**Issue by mynameistechno** [smooth-code/jest-puppeteer#123]
I looked at the create-react-app example and I'm able to get `jest-puppeteer` to work, but I can't seem to get it to read config from `jest-puppeteer.config.js` no matter where I put it (I also tried env var). E.g. I'd like it to launch the server before running the tests. Can you provide any information and/or update the example that demonstrates where to add the jest-puppeteer config? Thanks in advance!

**Comment by ctomacheski** [comment]
I have the same problem. Is there a way to use `jest-puppeteer.config.js` with create-react-app? I am trying to use jest-dev-server to launch my app before each test.

**Comment by neoziro** [comment]
The #111 will solve your problem, I will try to work on it soon.

**Comment by mynameistechno** [comment]
> The #111 will solve your problem, I will try to work on it soon.

Thanks @neoziro any ETA on this? Is it a large effort?
