### ISSUE TITLE
Not work well with setupTestFrameworkScriptFile in jest config

### ISSUE THREAD

**Issue by embbnux** [smooth-code/jest-puppeteer#125]
I want to update jest timeout global to wait Webpack dev server compiling codes.
So I add setupTestFrameworkScriptFile in jest config:

jest.config.js:
```
setupTestFrameworkScriptFile: '<rootDir>/jest.setup.js'
```

jest.setup.js:
```
jest.setTimeout(100000);
```

But after this, `await expect(page).toMatch('Page string');` throw `expect(string)[.not].toMatch(expected)`. ` page ` is a object.

```
  it('should display "RingCentral Embeddable" text on page', async () => {
    await page.goto(__HOST_URI__);
    await expect(page).toMatch('Page string'');
  });
```

If I set timeout in test, it works well:

```
  it('should display "RingCentral Embeddable" text on page', async () => {
    jest.setTimeout(100000);
    await page.goto(__HOST_URI__);
    await expect(page).toMatch('Page string'');
  });
```

**Comment by neoziro** [comment]
Thanks @Zoxive, I will not have said better.
