### ISSUE TITLE
Keep browser opened on failure

### ISSUE THREAD

**Issue by gregberge** [smooth-code/jest-puppeteer#130]
As suggested in #38, the idea is to intercept a test failure and stop the browser. It is not an easy task and it needs some research. Jest does not provide any API to intercept a test failure, so we have to hack it.

Maybe Jest team could help us to achieve that? @SimenB

#43 could also help to find a solution for this.

**Comment by SimenB** [comment]
>Jest does not provide any API to intercept a test failure, so we have to hack it.

What do you mean? Right now we just throw (unless you use `done` callback), so you could just replace `test` with your own function with built in `try-catch` I think?

Or do you want us to have a function on e.g. `testEnvironment`'s where it can intercept errors and either forward or swallow them?

**Comment by neoziro** [comment]
I think it would be better to be able to intercept an error in the test environment. I don’t want to invent another method than « it » and « test ». I could patch them but if every Jest plugin do it, it will become a jungle.

So your advice for now is to patch « it » and « test »?

**Comment by SimenB** [comment]
For now, yeah. You can open up a feature request with jest if you want, but I'm not sure if it'll be accepted. Some examples of the API you envision would be nice :)

**Comment by klase** [comment]
I've tried to wrap it with the following function:

`global.makeSure = (description, func) => {
  return it(description, async () => {
    try {
      await func();
    } catch (e) {
      console.log(page);
      await page.screenshot({ path: `screenshot.png` });
    }
  });
};`

The page object is accessible but I'm unable to take a screenshot. Does that mean puppeteer is shut down at this point?

**Comment by celador** [comment]
// jest.setup.js


global.it = async function(name, func) {
  return await test(name, async () => {
    try {
      await func();
    } catch (e) {
      await fs.ensureDir('e2e/screenshots');
      await page.screenshot({ path: `e2e/screenshots/${name}.png` });
      throw e;
    }
  });
};

**Comment by rodoabad** [comment]
We got an traction on this guys?

**Comment by cunio-martin** [comment]
> ```
> // jest.setup.js
> 
> global.it = async function(name, func) {
>   return await test(name, async () => {
>     try {
>       await func();
>     } catch (e) {
>       await fs.ensureDir('e2e/screenshots');
>       await page.screenshot({ path: `e2e/screenshots/${name}.png` });
>       throw e;
>     }
>   });
> };
> ```

for typescript users:
```
// jest.setup.ts

declare global {
  namespace NodeJS {
    interface Global {
      it: (name: any, func: any) => Promise<void>;
    }
  }
}

global.it = async function(name, func) {
  return await test(name, async () => {
    try {
      await func();
    } catch (e) {
      await ensureDir("screenshots");
      await page.screenshot({ path: `screenshots/${name}.png` });
      throw e;
    }
  });
};

```

**Comment by Mahanchello** [comment]
That works perfectly fine, the only question I have, after I start using that function for screenshots generation, i can't use it.only in tests, getting error `it.only is not a function`. Maybe someone knows what's wrong?

**Comment by pavoltravnik** [comment]
> That works perfectly fine, the only question I have, after I start using that function for screenshots generation, i can't use it.only in tests, getting error `it.only is not a function`. Maybe someone knows what's wrong? I'm using Jest

I suppose it is not chaining methods. Try this https://stackoverflow.com/questions/44446626/run-only-one-test-with-jest

**Comment by SimenB** [comment]
25.3.0 includes https://github.com/facebook/jest/pull/9397 which _should_ unblock both this and #131 without hacks

**Comment by FezVrasta** [comment]
@SimenB is there a solution for this problem as of today? I understand Jest now provides the necessary functionalities but I don't understand if jest-puppeteer makes use of them.

**Comment by sjurgis** [comment]
@Mahanchello you can do the following instead

```
global.it = Object.assign(async (name, func, timeout) => {
    return await test(name, async () => {
        try {
            await func();
        } catch (e) {
            if (page) {
                try {
                    await page.screenshot({path: `screenshots/${name}.png`});
                } catch (e) {
                    console.error(e)
                }
            }
            throw e;
        }
    }, timeout);
}, test)
```

**Comment by rajeshkumarp** [comment]
@sjurgis what if page is closed at that time? How can we get the screenshot?

**Comment by sjurgis** [comment]
I guess not. Only wanted to try this solution because I was reluctant to try jest-circus.
I've now switched to it and it's much easier and works better (we're actually using Playwright, not Pupeteer). It was as easy as adding `testEnvironment: "./jest.environment.js",` to our jest.config.js and then
```
const PlaywrightEnvironment = require('jest-playwright-preset/lib/PlaywrightEnvironment').default

class CustomEnvironment extends PlaywrightEnvironment {
    async handleTestEvent(event) {
        if (event.name === 'test_done' && event.test.errors.length > 0) {
            const parentName = event.test.parent.name.replace(/\W/g, '-')
            const specName = event.test.name.replace(/\W/g, '-')
            try {
                const url = this.global.page.url()
                if (this.global.page && url && url !== 'about:blank') {
                    await this.global.page.screenshot({
                        path: `screenshots/${parentName}_${specName}.png`,
                    })
                }
            } catch (e) {
                console.error(e)
            }
        }
    }
}

module.exports = CustomEnvironment

```

**Comment by saharso** [comment]
Why not simply use a very long timer to prevent the browser from closing?

**Comment by gregberge** [comment]
It will not happen. But we will take a screenshot.
