### ISSUE TITLE
Support incognito browser context

### ISSUE THREAD

**Issue by neoziro** [smooth-code/jest-puppeteer#133]
As suggested in #81 and as started in #83, we should support [incognito browser context](https://pptr.dev/#?product=Puppeteer&version=v1.8.0&show=api-browsercreateincognitobrowsercontext).

## Technical detail

Add `browserContext` in configuration and default to `default` context.

**Comment by jacobweber** [comment]
If anyone else is trying to do this in the current version (where this change hasn't been released yet), you can extend the environment, following the instructions in the Readme, and then add to the setup method:
```
await super.setup();
this.global.context = await this.global.browser.createIncognitoBrowserContext();
this.global.page = await this.global.context.newPage();
```
