### ISSUE TITLE
Do not open a new page at start

### ISSUE THREAD

**Issue by neoziro** [smooth-code/jest-puppeteer#136]
As suggested in #114, opening a new page is not required. We could use the current page to avoid opening tab.

https://github.com/smooth-code/jest-puppeteer/blob/1bb21add46cfbccc8054dec11bb47cfe59f6d98f/packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js#L43

**Comment by ohana54** [comment]
I tried tackling this but I'm not sure it will work.
If I have 2 test suites running in parallel, instead of each suite creating a new page, they will try to use the same one (the default one that is created when launching the browser).
Am I missing anything?

**Comment by neoziro** [comment]
Ah.. I think you are right, I don't know if this issue is possible. Can we know if there is two tests suites running parallel?

**Comment by ohana54** [comment]
We can maybe know or try to track it, but I personally wouldn't go there, it will probably be a source of crazy elusive bugs. IMO it's not worth it for this minor enhancement.
An alternative could be not to create a page at all (opt in of course), and leave it to the library consumer to decide. Again, not something I would do unless there's a demand for that.

**Comment by neoziro** [comment]
You are right, let's not do it.
