### ISSUE TITLE
Add "cwd" option to jest-dev-server setup

### ISSUE THREAD

**Issue by callumlocke** [smooth-code/jest-puppeteer#141]
## 🚀 Feature Proposal

I'd like to be able to choose the CWD for my server setup command to run in.

## Motivation

For monorepos with nonstandard structures.

## Example

```js
// global-setup.js
const { setup: setupDevServer } = require('jest-dev-server')

module.exports = async function globalSetup() {
  await setupDevServer({
    command: `node config/start.js --port=3000`,
    cwd: '/SOME/CUSTOM/DIR',
    launchTimeout: 50000,
    port: 3000,
  })
}
```

## Pitch

It's normal for any library that lets you run a command to let you specify where it will run.

---

By the way, thank you for separating the parts of jest-puppeteer into packages that are also individually useful. This project is really well designed. I'm using jest-dev-setup to run a test server and using [react-cosmos](https://github.com/react-cosmos/react-cosmos)/enzyme fixtures for the front-end side, so it's nice to be able to use jest-dev-server without pulling in anything Puppeteer-related.

**Comment by neoziro** [comment]
OK for this feature, your described it clearly, ready to implement for me!

**Comment by srounce** [comment]
Pass it into the options field of the `launch` object.
As per the docs it uses expects the same structure as [child_process](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options)

```javascript
module.exports = async function globalSetup() {
  await setupDevServer({
    command: `node config/start.js --port=3000`,
    options: {
        cwd: '/SOME/CUSTOM/DIR',
    },
    launchTimeout: 50000,
    port: 3000,
  })
}
```

**Comment by neoziro** [comment]
Yes @srounce is right! So it is already implemented!
