### ISSUE TITLE
Docs around Access globalSetup or globalTeardown incorrect

### ISSUE THREAD

**Issue by shwetasabne** [smooth-code/jest-puppeteer#15]
The docs around `Access globalSetup or globalTeardown` indicate using:
```bash
const {
  setup: setupPuppeteer,
  teardown: teardownPuppeteer,
} = require('jest-puppeteer')
```

However that throws an error:
```
Error: Cannot find module 'jest-puppeteer'
```

Instead using `require('jest-environment-puppeteer')` works as expected. 

Requesting that the docs be updated !

**Comment by neoziro** [comment]
Yeah, PR welcome! Thanks for spotting it!
