### ISSUE TITLE
expect(instance).toFill does not work correctly for textareas with multi-line contents

### ISSUE THREAD

**Issue by spinningarrow** [smooth-code/jest-puppeteer#150]
## 🐛 Bug Report

expect(instance).toFill does not work correctly for textareas with multi-line contents.

I think the underlying issue is that `toFille` uses a triple-click to select all the contents, which does not work with multi-line contents in a textarea.

## To Reproduce

1. Have a textarea element on the page that has a multi-line value
2. Use `expect(instance).toFill` on it to replace its contents

## Expected behavior

The entire content of the textarea is replaced by the new text from the test.

## Actual behavior

Only one line of the textarea is replaced.

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash

## System:
 - OS: macOS 10.14
 - CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 - Memory: 1.28 GB / 16.00 GB
 - Shell: 2.7.1 - /usr/local/bin/fish
## Binaries:
 - Node: 11.1.0 - /usr/local/bin/node
 - Yarn: 1.12.1 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
```

**Comment by srounce** [comment]
Do you have a repository that replicates this issue, I'd like to have a go at this bug sometime in the next few weeks.
