### ISSUE TITLE
Tests failing in CI

### ISSUE THREAD

**Issue by sorodrigo** [smooth-code/jest-puppeteer#155]
## 💬 Questions and Help

Jest Puppeteer project is young, but please before asking your question:

- Read carefully the README of the project
- Search if your answer has already been answered in old issues

After you can submit your question and we will be happy to help you!

Hello! I'm having an issue running Puppeteer and Jest together in travis CI. I've searched and tried all kind of things and can't find a solution. I wondering if anyone else has ran into this before. I keep having weird errors like the following:
<img width="265" alt="screen shot 2018-11-13 at 19 27 20" src="https://user-images.githubusercontent.com/12124839/48434645-9795bf80-e77a-11e8-91b9-fbef92e57829.png">
This happens using `test`, `test.each`, `it`. I've updated and tried different versions of babel and still can't make it work.

**Comment by neoziro** [comment]
Can you provide a reproducing repository? I don't have enough information to help you!

**Comment by sorodrigo** [comment]
yes sorry my project is open source so you can actually check the code and tests if that helps.
[failing test code 1](https://github.com/Vizzuality/trase/blob/c1039eb3cfdc9ba67bdb7bc33a90895435b97651/frontend/scripts/tests/puppeteer/profile-root.test.e2e.js)
[failing test code 2](https://github.com/Vizzuality/trase/blob/c1039eb3cfdc9ba67bdb7bc33a90895435b97651/frontend/scripts/tests/puppeteer/global-search.test.e2e.js)
[travis build 1](https://travis-ci.org/Vizzuality/trase/jobs/452454381)
[travis build 2](https://travis-ci.org/Vizzuality/trase/jobs/454626840)

**Comment by UziTech** [comment]
is this still an issue?

**Comment by sorodrigo** [comment]
I dont work in that project anymore, feel free to close.
