### ISSUE TITLE
jest-puppeteer relies on unsafe terminate 2.1.0

### ISSUE THREAD

**Issue by forestbelton** [smooth-code/jest-puppeteer#157]
`jest-puppeteer` uses `terminate` 2.1.0, which is vulnerable to a dependency attack through `ps-tree` 1.1.0. See https://github.com/dwyl/terminate/issues/35 for more information.

Is there any way we could use a different version or alternative library?

**Comment by shermango** [comment]
bump ^^^ --- original issue: https://github.com/dominictarr/event-stream/issues/116

**Comment by goodmind** [comment]
same

**Comment by yakovkhalinsky** [comment]
Our jenkins builds now fail as this package `flatmap-stream` seems to have been hard unpublished from npm.

Have had to remove `jest-puppeteer` for now till this gets resolved so our builds can pass.

**Comment by neoziro** [comment]
Fixed in v3.5.2

**Comment by yakovkhalinsky** [comment]
Thanks @neoziro for your quick response ❤️

**Comment by yakovkhalinsky** [comment]
And @xiaoyuhen I forgot to mention for their PR 👍
