### ISSUE TITLE
Add ability to right click and double click to toClick

### ISSUE THREAD

**Issue by cpchen** [smooth-code/jest-puppeteer#159]
## 🚀 Feature Proposal
Add ability to right click and double click to `toClick`.

## Motivation
Something similar to https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#mouseclickx-y-options

## Example

Add two configuration options to `toClick`, like

```
expect(page).toClick('button'), { button: 'right', clickCount: 2 }
```

## Pitch

Would be useful

**Comment by neoziro** [comment]
Options are already forwarded, you can already do it, see https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer/src/matchers/toClick.js

**Comment by cpchen** [comment]
You can't do this in typescript because the schema doesn't include the forwarded options.

**Comment by neoziro** [comment]
Types are not maintained in this repository, please fix it in definitely typed.
