### ISSUE TITLE
Add testEnvironment: "jsdom" requirement to the docs

### ISSUE THREAD

**Issue by grebenyuksv-preply** [smooth-code/jest-puppeteer#162]
## 🚀 Feature Proposal

Add `testEnvironment: "jsdom"` requirement to the docs

## Motivation

I've just spent many minutes trying to guess why the basic example from the readme caused `page is not defined` errors — I had `testEnvironment: "node"` set

**Comment by neoziro** [comment]
Hmm, I am surprised that it requires a `testEnvironement: "jsdom"` to run. Can you give more information about the error when using `testEnvironement: "jsdom"`?

**Comment by grebenyuksv-preply** [comment]
Sorry, my bad, it actually requires it _unset_:

```
  // The test environment that will be used for testing
  // testEnvironment: "jest-environment-jsdom",
```

**Comment by neoziro** [comment]
Ah yes, it is specified by preset of course.

**Comment by eddyoc** [comment]
Er... so.... what's the solution to the ```ReferenceError: page is not defined``` problem then?

**Comment by bidoubiwa** [comment]
@eddyoc I had the same problem. I realize it was because my script tag that imported another library did not work...
Maybe the error handler changed.

**Comment by bidoubiwa** [comment]
I had to refresh my yarn.lock
