### ISSUE TITLE
Remove the `terminate` dependency from `jest-dev-server`

### ISSUE THREAD

**Issue by Dilatorily** [smooth-code/jest-puppeteer#167]
## 🚀 Feature Proposal

Remove the `terminate` dependency from the `jest-dev-server` package.

## Motivation

The `terminate` library is licensed under GPL-2.0 and can make this project unusable in certain licensing situations.

## Example

It can be replaced with an MIT licensed library such as [`fkill`](https://www.npmjs.com/package/fkill).

## Pitch

Since `terminate` is an implicit dependency of `jest-puppeteer`, it makes it completely unusable in certain licensing scenarios for a feature that might not even be used.

**Comment by neoziro** [comment]
Hello @Dilatorily, why not if a library has a more permissive license with the same features offered by terminate, I don't see any objection to switch to it.
