### ISSUE TITLE
jest-puppeter example

### ISSUE THREAD

**Issue by xiaoyuhen** [smooth-code/jest-puppeteer#168]
## 💬 Questions and Help

The example provided by jest-puppeter is not too complete, maybe we can improve it?

https://github.com/smooth-code/jest-puppeteer/tree/master/examples/create-react-app

**Comment by neoziro** [comment]
Hello @xiaoyuhen, why not! Be my guest 😏😙

**Comment by xiaoyuhen** [comment]
This issue has not been fully completed and I will resolve it as soon as possible. Please don't close it. 👾
