### ISSUE TITLE
Add support for Firefox thx to puppeteer-firefox

### ISSUE THREAD

**Issue by tkrotoff** [smooth-code/jest-puppeteer#171]
Add support for Firefox thanks to [puppeteer-firefox](https://github.com/GoogleChrome/puppeteer/tree/master/experimental/puppeteer-firefox) :heart_eyes_cat:

**Comment by philipp-spiess** [comment]
I quickly tried to use `jest-puppeteer` with `puppeteer-firefox` by renaming `node_modules/puppeteer-firefox` to `node_modules/puppeteer` and I could run my (well, currently very limited set of) tests just fine!

Grepping for the `puppeteer` imports in this project it seems like this is limited to only these two lines:

**Comment by neoziro** [comment]
Hello @philipp-spiess, it's a very good news! I think we could provide support for it in future!

**Comment by yairEO** [comment]
Related to #312
