### ISSUE TITLE
Add Simplified Chinese translated docs

### ISSUE THREAD

**Issue by xiaoyuhen** [smooth-code/jest-puppeteer#174]
## 💬 Questions and Help
hi, @neoziro 

jest-puppeteer is a great project and I really like it.

What do you think about translations it to the other languages?

I would like to help with the translation into Simplified Chinese

**Comment by neoziro** [comment]
Hello @xiaoyuhen, it would be awesome to have docs translated in chinese. I don't know if it is possible to do it. I let you give a look to https://github.com/smooth-code/smooth-doc and `website` folder in this repository.

**Comment by xiaoyuhen** [comment]
hi, @neoziro 
I just finished the vacation and I am very sorry to reply so long.

I will look at smooth-doc first, then plan how to do it.
