### ISSUE TITLE
wrong timeout when using jestPuppeteer.debug()

### ISSUE THREAD

**Issue by BetterCallSky** [smooth-code/jest-puppeteer#184]
## 🐛 Bug Report

The timeout is wrong when using `jestPuppeteer.debug()`. 

https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js#L69

```
// Set timeout to 4 days
this.setTimeout(345600)
```
4 days = 345600 seconds
The above method accepts ms, so it should be multipled by 1000.

![image](https://user-images.githubusercontent.com/4478684/51250340-5c8c5400-1996-11e9-82ad-a77d2aedf26e.png)

**Comment by xiaoyuhen** [comment]
hi, @BetterCallSky, will be fixed in https://github.com/smooth-code/jest-puppeteer/pull/185
