### ISSUE TITLE
Too many tabs

### ISSUE THREAD

**Issue by linvain** [smooth-code/jest-puppeteer#187]
## 🐛 Bug Report

1) jest-puppeteer doesn't use first (initial) tab, leaving it forever empty
2) jest-puppeteer opens a tab for every test file, even if the test doesn't use puppeteer

## Expected behavior

1) jest-puppeteer should not create new tab for the first test
2) jest-puppeteer should create tabs only for tests that use puppeteer.
Maybe do not expose `page` and let user create new tabs explicitly?

## System info

```bash
## System:
 - OS: Linux 4.20 Arch Linux undefined
 - CPU: (4) x64 Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz
 - Memory: 1.61 GB / 5.73 GB
 - Container: Yes
 - Shell: 5.0.0 - /bin/bash
## Binaries:
 - Node: 11.7.0 - /usr/bin/node
 - Yarn: 1.13.0 - /usr/bin/yarn
 - npm: 6.6.0 - /usr/bin/npm
## npmPackages:
 - jest-puppeteer: ^3.8.0 => 3.8.0
```

**Comment by neoziro** [comment]
Hello @linvain, we are aware of this, but we choose to let it like it is. You can find the history of the discussion about it in #136.
