### ISSUE TITLE
jest-puppeteer.config.js not in the root

### ISSUE THREAD

**Issue by Diokuz** [smooth-code/jest-puppeteer#19]
I want to place `jest-puppeteer.config.js` to custom folder. How could I tell that to jest-puppeteer?

**Comment by neoziro** [comment]
Unfortunately for now you can't, same as Jest I think. You can create different configuration using environment variables.

**Comment by Diokuz** [comment]
Jest can be launched with custom config:

```
./node_modules/.bin/jest --config ./puppeteer/jest.config.js
```

**Comment by neoziro** [comment]
Right now it is not possible to implement:

- [`testEnvironmentOptions`](https://facebook.github.io/jest/docs/en/configuration.html#testenvironmentoptions-object) are not passed to "globalSetup" and "globalTeardown", so impossible to use it to specify config
- Jest does not authorize to add cli options

**Comment by Diokuz** [comment]
What about environment variable?

```
JEST_PUPPETEER_CONFIG=some/path/to/config.js jest --maxWorkers=1
```

**Comment by neoziro** [comment]
Good idea!
