### ISSUE TITLE
expect(page).toMatch gives matcher error - expected string but got object

### ISSUE THREAD

**Issue by Greg-oliver99** [smooth-code/jest-puppeteer#193]
## 🐛 Bug Report

**Running this simple test -** 
```
describe('Totaljobs', () => {
    beforeAll(async () => {
        await page.goto('https://www.totaljobs.com');
    });

    it('should display "job ads" somewhere on the page', async () => {
        await expect(page).toMatch('job ads');
    });
});
```
with this version of jest - 
package.json
```
{
  "name": "pj-demo",
  "version": "1.0.0",
  "description": "demo",
  "main": "totaljobs.test.js",
  "dependencies": {},
  "devDependencies": {
    "jest": "^24.0.0",
    "jest-puppeteer": "^3.9.0",
    "puppeteer": "^1.11.0"
  },
  "scripts": {
    "test": "jest"
  },
  "jest": {
    "preset": "jest-puppeteer"
  },
  "author": "",
  "license": "ISC"
}
```
**fails with error -** 
 FAIL  ./totaljobs.test.js
  Totaljobs
    × should display "job ads" somewhere on the page (258ms)

  ● Totaljobs › should display "job ads" somewhere on the page

    expect(received).toMatch(expected)

    Matcher error: received value must be a string

    Received has type:  object
    Received has value: {"_accessibility": {"_client": [CDPSession]}, "_client": {"_callbacks": [Map], "_connection" .......

Running with an earlier version of jest works fine - 
package,json
```
{
  "name": "pj-demo",
  "version": "1.0.0",
  "description": "demo",
  "main": "totaljobs.test.js",
  "dependencies": {},
  "devDependencies": {
    "jest": "^23.6.0",
    "jest-puppeteer": "^3.9.0",
    "puppeteer": "^1.11.0"
  },
  "scripts": {
    "test": "jest"
  },
  "jest": {
    "preset": "jest-puppeteer"
  },
  "author": "",
  "license": "ISC"
}
```

**Comment by xiaoyuhen** [comment]
hi, @Greg-oliver99 

Thank you very much for reporting this bug.

It seems that it was caused by the Jest@24 version, and we will fix the issue related to Jest@24 as soon as possible this week.

I suggest you use Jest@23.6 now.

**Comment by xiaoyuhen** [comment]
hi @Greg-oliver99 

`jest-puppeteer` are support jest v24 now.

you can use ```jest-puppeteer@4.x``` to resolve this bug

**Comment by debugtalk** [comment]
@xiaoyuhen I met the same issue again.

```
"jest": "^24.8.0",
"jest-puppeteer": "^4.2.0",
"puppeteer": "^1.17.0"
```

**Comment by liu-xiao-cui** [comment]
met same error

```
puppeteer: 2.0.0,
jest: 24.9.0,
jest-puppeteer: 4.3.0
```
