### ISSUE TITLE
create-react-app example fails (timeout)

### ISSUE THREAD

**Issue by lmenus** [smooth-code/jest-puppeteer#199]
## 💬 Questions and Help

I cloned `examples/create-react-app` folder from this repository to test this integration. Run `npm i` to install dependencies and then `npm run test:integration`. It appears all tests but the first one work. I arrived at this conclusion by progressively disabling the first test from the sample file and the result was always the same.

```js

  ● app › should match a input with a "textInput" name then fill it with 
text

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      at mapper (../node_modules/jest-jasmine2/build/queue_runner.js:41:52)

  ● app › should match a input with a "textInput" name then fill it with text

    Error

      Error: Execution context was destroyed, most likely because of a navigation.
```

The failing test context obviously changes, but the error message is always the same down to the offending line. Can anyone point out what I am missing here? Thanks!

**Comment by xiaoyuhen** [comment]
please try to use ```yarn``` to install package

**Comment by xiaoyuhen** [comment]
hi @lmenus
