### ISSUE TITLE
slowMo not working

### ISSUE THREAD

**Issue by Diokuz** [smooth-code/jest-puppeteer#20]
My root `jest-puppeteer.config.js`:

```js
const isDev = true

module.exports = {
  server: {
    command: 'node puppeteer/server.js',
    port: 1337,
  },
  launch: {
    // dumpio: true,
    slowMo: 1200,
    headless: !isDev,
    executablePath: isDev ? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' : undefined,
  },
}
```

But no `slowMo` detected: tests are executed as fast as possible, nothing can be observed. Is there any secrets on how to switch on the `slowMo` flag?

**Comment by neoziro** [comment]
I just tested it and it does not work, it should be a Puppeteer issue because, all options specified in `launch` are passed to `Puppeteer.launch`, is this option working without Jest Puppeteer?

**Comment by k3mayo** [comment]
You can also set the slowMo property in the options object parameter for `puppeteer.connect`. I believe this is missing in the `PuppeteerEnvironment` class where `puppeteer.connect` is called.
