### ISSUE TITLE
toClick timeout option is NOT respected.

### ISSUE THREAD

**Issue by BenjaminCaffrey** [smooth-code/jest-puppeteer#202]
Hi all,

I have just begun E2E testing with jest-puppeteer and expect-puppeteer. I write the following test:

```
  it(`should click LET'S GO`, async () => {
    await jestPuppeteer.debug();
    await expect(page).toClick('button', {text: `LET'S GO`})
    await jestPuppeteer.debug();
  }, 90000);
```

As expected, jestPuppeteer pauses code execution, allowing me press enter to resume. I click enter, execution resumes momentarily prior to another debug pause. I check Chromium (headless: false in this case) to ensure the button was clicked (it was), and click enter again so tests can finish:

![image](https://user-images.githubusercontent.com/42548278/52886980-51fae100-3133-11e9-8698-10c21990632a.png)

So I feel confident in this case that after log-in, the page exposes a button with text `LET'S GO`.

I attempt using the `timeout` option to wait until this button is exposed to click as specified in the API:

```
  it(`should click LET'S GO`, async () => {
    await expect(page).toClick('button', {text: `LET'S GO`, timeout: 30000})
    await jestPuppeteer.debug();
  }, 90000);
```

Here I experiment with a long timeout (the button _should_ appear after only 3-4 seconds). 

Unfortunately now the tests log-in my user and, within the default 500ms, throw an error that there is no `LET'S GO` button, despite the timeout I have set:

![image](https://user-images.githubusercontent.com/42548278/52887240-3a702800-3134-11e9-9e31-90150e887e67.png)

How can I correctly use timeout? Is there a better general approach?

Thank you and I appreciate any input!

**Comment by xiaoyuhen** [comment]
hi @BenjaminCaffrey 

The ```toClick``` function does not support the timeout option. If you want to delay 3-4 seconds, you can use ```jest.waitFor```


```
 it(`should click LET'S GO`, async () => {
    await page.waitFor(3000)
    await expect(page).toClick('button', {text: `LET'S GO`})
    await jestPuppeteer.debug();
  }, 90000);
```

**Comment by BenjaminCaffrey** [comment]
Awesome @xiaoyuhen , thank you for the feedback! Your suggested approach works well.

Should the docs be altered if toClick does not support timeout?

![image](https://user-images.githubusercontent.com/42548278/52961064-5a336600-3357-11e9-870a-722d765476cb.png)

**Comment by xiaoyuhen** [comment]
hi @BenjaminCaffrey 

The docs seem wrong, ```polling``` and ```timeout``` are both not support. maybe ```puppeteer``` changes the API but we forget to change the docs.


we will check all the docs on this weekend. thank you for your reporting. 

cc @neoziro

**Comment by neoziro** [comment]
Hmm yes we have to test that. @xiaoyuhen do you take it?

**Comment by xiaoyuhen** [comment]
@neoziro 

yeah, I will check the docs on this weekend

**Comment by neoziro** [comment]
Thanks!
