### ISSUE TITLE
Take a screenshot when test fails and send it via my "slack" reporter

### ISSUE THREAD

**Issue by galtubi91** [smooth-code/jest-puppeteer#206]
Hey
Im using a slack reporter that sends text message when one or more of my tests fail. my question is there a way to take a screenshot of the page only when the test failed?

**Comment by xiaoyuhen** [comment]
hi @galtubi91 

its have some difficulty about this case, see https://github.com/smooth-code/jest-puppeteer/issues/131

**Comment by neoziro** [comment]
Follow up in #131
