### ISSUE TITLE
Add visibility flag to toMatchElement config

### ISSUE THREAD

**Issue by Aaron-Pool** [smooth-code/jest-puppeteer#207]
## 🚀 Feature Proposal

A `visibility` flag on the `toMatchElement` config to signal that the matcher should continue to wait until _both_ the selector is on the page _and_ it doesn't have `visibility: hidden` or `display: none` set.

## Motivation

The puppeteer `waitForSelector` api has a `visibility` flag, that, in addition to waiting for the presence of a selector on screen, also ensures that it has neither `visibility: hidden` or `display: none` property set. Could we get this behavior on the `toMatchElement` config? It would be very convenient when, for example, I'm waiting to click on something.

## Example

```js
await expect(page).toMatchSelector('card', { visibility: true});
```

## Pitch

Why does this feature belong in the Jest Puppeteer ecosystem? To maintain parody with selector searching in the `puppeteer` ecosystem.

**Comment by neoziro** [comment]
I think it is a great improvement, I have to think how to handle it correctly.

**Comment by neoziro** [comment]
@xiaoyuhen what do you think?

**Comment by xiaoyuhen** [comment]
@neoziro 

its very useful feature, I will add this feature on tomorrow
