### ISSUE TITLE
Unable to set timeout globally for expect-puppeteer

### ISSUE THREAD

**Issue by bluedusk** [smooth-code/jest-puppeteer#209]
Hi guys,
I'm trying to set global timeout for expect-puppeteer because I got 500ms timeout error.
Its only work if I set separately in each *.test.js file (setDefaultOptions({ timeout: 1000 }),
I tried set this in my environment file but not working:
```
const PuppeteerEnvironment = require("jest-environment-puppeteer")
const { setDefaultOptions,getDefaultOptions } = require('expect-puppeteer')

setDefaultOptions({ timeout: 1000 }) // this will not work
	
module.exports = class extends PuppeteerEnvironment {
	async setup() {
		await super.setup()
		try {
		setDefaultOptions({ timeout: 1000 }) // this will not work

		} catch (error) {
			console.error(error)
			throw error
		}
	}

	async teardown() {
	...
	}
}

```

**Comment by xiaoyuhen** [comment]
hi @bluedusk 

```setDefaultOptions``` is a global variable by ```jest-puppeteer```

but you want to set this global variable on ``jest``` context, definitely, it doesnt work.

if you want to set global timeout, try use jest ```setupFilesAfterEnv```

```
// jest.config.js
module.exports = {
  setupFilesAfterEnv: ['./setupTestFramework.js'],
}
```


```
// setupTestFramework.js
// wait for 20s before failing a test
jest.setTimeout(20 * 1000)
```
