### ISSUE TITLE
How to pass process.env to jest-puppeteer.config ?

### ISSUE THREAD

**Issue by Diokuz** [smooth-code/jest-puppeteer#21]
I tried to launch puppeteer with

```
PUPPETEER_SLOW=1 ./node_modules/.bin/jest --config ./puppeteer/jest.config.js
```

But `PUPPETEER_SLOW` not in `process.env` in `./jest-puppeteer.config.js`. Why?

```js
console.log(process.env.PUPPETEER_SLOW) // undefined

module.exports = {
  server: {
    command: 'node puppeteer/server.js',
    port: 1337,
  },
  launch: {
...
```

**Comment by neoziro** [comment]
I just tested it and it works very well, also I use it on all my projects. Config is loaded using a standard `require` (https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-environment-puppeteer/src/readConfig.js#L26).
