### ISSUE TITLE
Use server origin by default

### ISSUE THREAD

**Issue by jamesarosen** [smooth-code/jest-puppeteer#214]
## 🚀 Feature Proposal

I would love to be able to do `page.goto('/')` instead of `page.goto('http://localhost:3000/')`. Currently if I try that I get

```
Protocol error (Page.navigate): Cannot navigate to invalid URL

      1 | describe('MyApp: /', () => {
      2 |   beforeAll(async () => {
    > 3 |     await page.goto('/')
        |                ^
      4 |   })
```

## Motivation

Not having to specify the protocol, host, and port in each test makes tests easier to write. It also makes it easier to change the way all tests are run, e.g. changing `http:` to `https:`.

## Example

```js
// jest-puppeteer.config.js:
module.exports = {
  server: {
    command: 'yarn run start',
    port: 3000,
  },
}

// if no origin is provided, use the one from the jest-puppeteer config:
await page.goto('/')

// but you can always tell the browser to go elsewhere if needed:
await page.goto('https://some-third-party-provider.com')
```

## Pitch

Jest Puppeteer already knows about the protocol, host, and port from `jest-puppeteer.config.js`. It can use this information to make writing tests easier.

**Comment by jamesarosen** [comment]
I can sort of do this with a custom environment:
```js
const PuppeteerEnvironment = require('jest-environment-puppeteer')

class CustomEnvironment extends PuppeteerEnvironment {
  async setup() {
    await super.setup()
    const { port } = this.global.puppeteerConfig.server

    const originalGoto = this.global.page.goto
    this.global.page.goto = async function goto(pathOrURL) {
      const url = /^\//.test(pathOrURL)
        ? `http://localhost:${port}${pathOrURL}`
        : pathOrURL
      return originalGoto.call(this, url)
    }
  }
}

module.exports = CustomEnvironment
```

**Comment by xiaoyuhen** [comment]
hi @jamesarosen 

Very useful feature and a very nice solution. Could you take a PR to do this?

**Comment by jamesarosen** [comment]
It's not too hard to add the functionality, but I'm having a bit of trouble testing it. If I change `jest-puppeteer.config.js` in order to test this feature, it will break other tests. There's a `tests/__fixtures__/` directory with configurations, but I don't know how to _use_ one in a test.

**Comment by xiaoyuhen** [comment]
hi @jamesarosen 

Maybe you can submit your PR; then, then we can find why it will break other tests.

**Comment by lukaszfiszer** [comment]
Modifying public API of objects from a 3rd party module is always a bad idea. 

There are many non-intrusive ways to achieve exactly the same result:

```
async function goto(path) {
    await page.goto('http://localhost:3000' + path)
}

goto('/my/path')
```
or 

```
const getUrl = (path)  => 'http://localhost:3000' + path;

await page.goto(getUrl('/my/path'));
```

or 
```
const ORIGIN = 'http://localhost:3000';

await page.goto(ORIGIN  + /my/path);
```

**Comment by jamesarosen** [comment]
One downside of each of the solutions @lukaszfiszer suggests is that the origin is duplicated between `jest-puppeteer.config.js` and the helper definition. Of course, it's possible to put the origin in another file and import it in both places.
