### ISSUE TITLE
Starting my own server - server.js ?

### ISSUE THREAD

**Issue by campa** [smooth-code/jest-puppeteer#216]
I'm trying to start server for my tests, but I have not a server.js file in my project ? How can I create it ? 

```
> JEST_PUPPETEER_CONFIG=e2e/jest-puppeteer.config.js jest --config=e2e/jest.e2e.config.js 

Determining test suites to run...internal/modules/cjs/loader.js:583 throw err; 
^ Error: Cannot find module /media/[my-path]/server.js
```

Any suggestion ?

**Comment by xiaoyuhen** [comment]
hi, @campa 

> but I have not a server.js file in my project? 

I can't understand your description. Do you mead your project is a static HTML and don't need a server to launch it?

**Comment by campa** [comment]
I have a complete angular 7 project,  and I' migrating e2e tests from protactor & C to jest-puppeteer .

In your examples there is always a server.js file to start a server, but I cannot understand if I have to write it myself or there is a template compatible to your useful jest-puppeteer / jest-puppeteer server to follow.
Or it is packaged with some libs I have not. Hope I had clarified my context.

I'm sorry , I'm new with these kind of suff and terminology.

**Comment by xiaoyuhen** [comment]
hi @campa 

I know what you mean.
```
module.exports = {
  server: {
    command: 'node server.js',
    port: 4444,
  },
}
```

The command ```node server.js``` are not mean you should have a server.js file. its just an example.


In your case, May be you can use ```ng serve```.  see https://angular.io/guide/quickstart#step-3-serve-the-application
