### ISSUE TITLE
Unknown option "setupFilesAfterEnv" error when running my test file

### ISSUE THREAD

**Issue by galtubi91** [smooth-code/jest-puppeteer#218]
Hey
Im using jest-puppeteer (version 4.1.0). when running my tests i got that alert:

Deprecation Warning:
"setupTestFrameworkScriptFile" was replaced by configuration "setupFilesAfterEnv", which supports multiple paths.
 Please update your configuration.

but when i replace "setupTestFrameworkScriptFile" with: "setupFilesAfterEnv" i get this error:

Unknown option "setupFilesAfterEnv" with value "<rootDir>/reporters/screenshot.js" was found.
This is probably a typing mistake. Fixing it will remove this message.

this is my jest.config.js file content:
```
module.exports = {
  preset: 'jest-puppeteer',
  globalTeardown: './teardown.js',
  reporters: [
    'default',
    './reporters/slack',
  ],
  setupFilesAfterEnv: ['<rootDir>/reporters/screenshot.js'],
};
```

what am i doing wrong here? (probably something stupid that im missing)

Thanks

**Comment by xiaoyuhen** [comment]
hi @galtubi91 

Could you please give us a demo to check this?

**Comment by lukaszfiszer** [comment]
I guess `reporters` dir is located in your project folder. If yes, try relative path:
```
setupFilesAfterEnv: ['./reporters/screenshot.js'],
```

**Comment by galtubi91** [comment]
i tried that and it still throws that warning. what kind of demo do you need?
this what my project looks like:

![Screen_Shot_2019-04-04_at_3_29_06_PM](https://user-images.githubusercontent.com/22723999/55555856-dbb83b00-56ee-11e9-937d-e3375f6e2189.jpg)

what more information can i provide you?

Thanks

**Comment by Bhavikpatel576** [comment]
I had a similar issue that I also wasn't able to resolve. 

```Validation Warning:

  Unknown option "setupFilesAfterEnv" with value ["./test/jest.timeoutSetup.js"] was found.
  This is probably a typing mistake. Fixing it will remove this message. ```

**Comment by xiaoyuhen** [comment]
hi @galtubi91 

this PR works well https://github.com/galtubi91/automation-demo/pull/1

Maybe your screenshot.js is wrong,I dont know.

You can push your code on automation-demo,so I can know what happend.

**Comment by xiaoyuhen** [comment]
hi @backbone87 

Could you create a demo for us to check? If its possible.

**Comment by backbone87** [comment]
@xiaoyuhen wrong @ mention?

**Comment by xiaoyuhen** [comment]
@backbone87 

I am very sorry to bother you, made a mistake.

**Comment by galtubi91** [comment]
Hey @xiaoyuhen 
i pushed my changes. about the screenshot.js file, i don't think its related to its content because jest doesn't even run it because my console log at the top of the file isn't printed . 

https://github.com/galtubi91/automation-demo

thanks for your help man

**Comment by lcpereira** [comment]
I solved this problem by upgrading to the latest version of Jest 24.7.1

**Comment by Tycholiz** [comment]
can you confirm that jest-cli is at least v24? upgrading seemed to do the trick for me

**Comment by steveswork** [comment]
Unknown configuration option errors are usually related to version mismatch. Reconciling your version with the minimal jest version that supports the unknown configuration will be an advisable starting point.

If the problem persists, then a deeper look may be warranted. In this case, while the jest-puppeteer version may have thrown the deprecation warning regarding the configuration option, the jest configuration processor is ultimately responsible processing the configuration options and  setting up the jest environment.

The question then becomes whether the said processor is run by the jest-puppeteer or by jest itself. If by jest-puppeteer, which by the way is a highly dubitable assumption to make, then it would have easily recognized the very same configuration option it suggested.

However, if the configuration processor is run by jest framework, which is very much likely to be the case, then can the jest version you are currently using recognize and process the configuration option in question? If not, upgrade to the jest version that can, if you can.

**Comment by galtubi91** [comment]
@steveswork thanks a lot for your answer! actually when i upgraded jest-cli to latest version it solved the problem..

but thank you anyway 🙏

**Comment by steveswork** [comment]
@galtubi91 True, it is totally understandable. jest-cli is the jest dependency responsible to configuration processing among other things. You could use the opportunity also to upgrade your jest installation if it would not cause breaking changes in your tests. That's what I usually do. Upgrades tend to have current updates for bugs and security vulnerabilities when they exist.

Great work though.

**Comment by chenxiaoyao6228** [comment]
I got the same issue here when setting up custom jasmine setting, have tried to updated my jest-cli version to lastest but failed, here are my setting files:
jest config in package.json file
```js
  "jest": {
    "transform": {
      ".(ts|tsx)": "ts-jest"
    },
    "testEnvironment": "jsdom",
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "/test/"
    ],
    "coverageThreshold": {
      "global": {
        "branches": 90,
        "functions": 95,
        "lines": 95,
        "statements": 95
      }
    },
    "collectCoverageFrom": [
      "src/*.{js,ts}"
    ],
    "setupFilesAfterEnv": [
      "<rootDir>/test/boot.js"
    ]
  },
```
boot.ts
```js
console.log('excute...............................................................................................................');
const JasmineCore = require('jasmine-core')
// @ts-ignore
global.getJasmineRequireObj = function () {
  return JasmineCore
}
require('jasmine-ajax')

```
please correct if I've done anything wrong, thanks in advance!

**Comment by steveswork** [comment]
@chenxiaoyao6228 did you get error messages when running it? Could you update your post with the error message as well?
