### ISSUE TITLE
How to fix TS2339: Property 'browser' does not exist on type 'Global'?

### ISSUE THREAD

**Issue by sinapsist** [smooth-code/jest-puppeteer#221]
Dear jest-puppeteer community,

I am using typescript and configured jest-puppeteer using next configuration:
(without configuring custom setup and teardown)

jest-puppeteer.config.js
```
module.exports = {
    launch: {
        headless: false,
    }
}
```
jest.breakpoints.config.js
```
module.exports = {
    preset: 'jest-puppeteer',
    testRegex: './breakpoints/',
}
```
And test file:
```
beforeAll(async () => {
    //  Getting TS2339: Property 'browser' does not exist on type 'Global
    page = await global.browser.newPage();
    script = `getComputedStyle(document.querySelector('img[alt="Google"]', null)).display`;
});

afterAll(async () => {
    await page.close();
});

describe('Breakpoint test', () => {
    it('should not display right nav at mobile breakpoint', async () => {
        page.setViewport({ width: 400, height: 600 });
        await page.goto('https://www.google.com/');
        const result = await page.evaluate(script);
        expect(result).not.toBeNull()
    }, 10000);
});
```

And it works. but I am getting this TS2339 tslint error. Could someone, please, help me to understand how to fix it without  disabling TS-lint on this line.

Thank you!

**Comment by neoziro** [comment]
Hello @sinapsist, I don't know Typescript but I am sure someone would be able to help you.

**Comment by xiaoyuhen** [comment]
it's not an elegant solution, but you can add this code to solve this problem.

```
declare var global: any
```

**Comment by xiaoyuhen** [comment]
by the way, Should we add some Declaration Files(d.ts)? Its very useful. @neoziro

**Comment by neoziro** [comment]
@xiaoyuhen if you are up to maintain it, yes it could be great. On my side, I don't use Typescript and I can't edit any Typescript file.

**Comment by xiaoyuhen** [comment]
@neoziro 

yeah, I create an issue to about that https://github.com/smooth-code/jest-puppeteer/issues/224

**Comment by lukaszfiszer** [comment]
@sinapsist You can get TS definition for jest-puppeteer from this package: https://www.npmjs.com/package/@types/jest-environment-puppeteer
