### ISSUE TITLE
Bundle TypeScript definitions

### ISSUE THREAD

**Issue by xiaoyuhen** [smooth-code/jest-puppeteer#224]
## 🚀 Feature Proposal

add bundle TypeScript definitions

see https://github.com/smooth-code/jest-puppeteer/issues/221

**Comment by lukaszfiszer** [comment]
There are already TS definitions for  jest-puppeteer, but in a separate package: https://www.npmjs.com/package/@types/jest-environment-puppeteer

If you want to bundle them, it would make sense to ping the original author @JoshuaKGoldberg first.

**Comment by JoshuaKGoldberg** [comment]
Hi! It's often not a good idea to bundle type definitions with a package if the package's author(s) don't write it in TypeScript already. Definitions get out of date easily and being tied into the package's release cycle can slow down updates. Keeping them on DefinitelyTyped means we get the automated process & crowdsourced reviews of that repository.

**Comment by becky26** [comment]
Questions for author @JoshuaKGoldberg , since there is major update in the js version (e.g.: include visibility option in .toMatchElement function), would there be any update in the Typescript definition too? thank you!

**Comment by neoziro** [comment]
We will not bundle types in this library, I am not a TypeScript expert and I don't want to deal with TypeScript issues. It is better to have them in a separated repository maintained by the TypeScript community.

**Comment by JoshuaKGoldberg** [comment]
@becky26 feel free to file an issue on DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped

It's always accepting PRs for updates to libraries
