### ISSUE TITLE
Critical: Synchronous use toMatch() from jasmine fails silently when using expect-puppeteer

### ISSUE THREAD

**Issue by cburgmer** [smooth-code/jest-puppeteer#226]
## 🐛 Bug Report

Including expect-puppeteer with jest via `setupFilesAfterEnv` will silently replace jest's own synchronous `toMatch()` matcher (https://jestjs.io/docs/en/using-matchers#strings).

## To Reproduce

Run a test with an existing `expect('my text').toMatch('not the text');` but include expect-puppeteer now.

```
 PASS  tests/my-spec.js
(node:75012) UnhandledPromiseRejectionWarning: Error: Text not found "not the text"
```
## Expected behavior

The test should fail, and not simply show a warning

**Comment by xiaoyuhen** [comment]
hi  @cburgmer 

I try to test your case, but I get a fail error.

![image](https://user-images.githubusercontent.com/11402392/55854097-34c41b00-5b96-11e9-95cb-cc37a91f973c.png)

Could you please give me a demo to check this?

**Comment by cburgmer** [comment]
Sorry, only later did I realise that this issue seems to be slightly different:
`.toMatch()` behaves differently depending on the type passed into `expect()` - synchronously if the parameter is a string or I guess other simple types, asynchronously if the input is a promise.

This is obvious, if you have a stupid simple example like the one I posed above. Less so if you have more code going on, and you can't directly infer the type in play.

Consider

```js
expect(myPage.getUsername()).toMatch('myuser@example.com');
```

What happens if the implementation of `getUsername()` changes to return a Promise instead of a string? The test will certainly not fail (needs `await` for that new behaviour), and might not log a warning if the expect-puppeteer matcher is still able to extract this string. Only later, when a regression slips in, there you'll see a (rather silent) 'rejected promise' warning, not failing the test.

Let my thusly reword the issue: "Usability: toMatch changes synchronous/asynchronous behaviour depending on parameter passed".

May I argue that this is can be a terrible trap for your users. Maybe TypeScript makes this more visible (I guess not), but for pure JS there is no inspection that I know of that will flag this issue.

**Comment by neoziro** [comment]
Welcome in JavaScript @cburgmer 🤗

**Comment by xiaoyuhen** [comment]
I don't think TS will solve this problem.

Actually, The Developers may enter any value or type, I don't think jest-puppeteer needs to handle it all.

**Comment by cburgmer** [comment]
Well, you could rename the `toMatch()` method as to make it clear it's doing something completely different.

**Comment by neoziro** [comment]
@cburgmer you are right. We should rename it in the next major to avoid confusion.
