### ISSUE TITLE
wait-on checks strict ssl

### ISSUE THREAD

**Issue by Schnueggel** [smooth-code/jest-puppeteer#228]
## 🐛 Bug Report

The new package wait-on checks with strictSSL set to true. Our dev servers have self signed certs. Now test never starts and the server timeout triggers. Perhaps it would be good to set strictSSL: false, which is ok for dev, or give the option to do so

## To Reproduce

Use selfsigned endpoint

## Expected behavior

I expect that strict ssl checking is disabled or can be disabled for development purpose

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
 - CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
 - Memory: 1.66 GB / 15.35 GB
 - Container: Yes
 - Shell: 4.4.19 - /bin/bash
## Binaries:
 - Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
## npmPackages:
 - expect-puppeteer: ^4.1.1 => 4.1.1 
 - jest-dev-server: ^4.1.1 => 4.1.1 
 - jest-puppeteer: ^4.1.0 => 4.1.0 
```

**Comment by xiaoyuhen** [comment]
hi @Schnueggel 

Very sorry about that, the test case is not complete, so I don't handle the strictSSL case.

Please use the v4.1.0 now, and I will fix this issue as soon as possible.
