### ISSUE TITLE
Please write a tutorial on the CRA example if possible

### ISSUE THREAD

**Issue by TomasHubelbauer** [smooth-code/jest-puppeteer#230]
I appreciate that a CRA example has been included in the project, but I am wondering whether its README could be fleshed out? The README as it stands right now is a good resource and it is probably possible to recreate the CRA example following it, which is what I am going to try if this issue gets closed, but I'd feel more comfortable knowing I got it right if there was a checklist or a short guide to follow.

What I have in mind is a list of steps going from `create-react-app` to having the example as it is now in incremental steps. Reverse engineering this example is probably also possible, but again, it would be IMO better if this was provided in this repo as I personally and I am sure many others would feel more comfortable following such guide and knowing it was put together when rather than hacking it together ourselves and hoping our replication was correct.

What do you think?

**Comment by neoziro** [comment]
Hello @TomasHubelbauer, improving documentation is always a good thing for me. I don't have time to write it but feel free to submit a PR about it.

**Comment by TomasHubelbauer** [comment]
I will try to put together something as I understand it for your review so you can confirm whether I got it right.

**Comment by dvc009** [comment]
@TomasHubelbauer Were you able to put up this doc? Stuck on this for a while now :(

**Comment by TomasHubelbauer** [comment]
Unfortunately not, at the time it was a bit over my head and I've since not needed to revisit it. That said I would love to have a solution for this, too, just to know that when I do there will be something proven so I don't need to do the guess work again.

**Comment by TomasHubelbauer** [comment]
I just came across this: https://github.com/xfumihiro/jest-puppeteer-example
I won't look into it for the time being as I don't need this currently, but @dvc009 you might be interested.

**Comment by TomasHubelbauer** [comment]
A few more resources have cropped up, I am going to close the issue now and whoever lands here from a search engine can take a look at these:

- https://blog.scottlogic.com/2020/01/22/react-app-puppeteer.html
- https://kelvinmwinuka.com/testing-react-app-with-jest-puppeteer/
- https://jestjs.io/docs/puppeteer
