### ISSUE TITLE
wait-on issue doesn't play well with webpack-dev-server

### ISSUE THREAD

**Issue by hegelstad** [smooth-code/jest-puppeteer#236]
## Last working version
Worked up to version: 4.0.0

Stopped working in version: 4.0.0

## To Reproduce

Use `webpack-dev-server` and expect tests to start after compilation
The new `wait-on` package will not be able to parse the ok 200 status because it only listens for HEAD requests not GET requests... see https://github.com/bahmutov/start-server-and-test#note-for-webpack-dev-server-users

## Expected behavior

It should work like before changing to `wait-on`

```bash
*** Clipboard option removed - use clipboardy or clipboard-cli directly ***


## System:
 - OS: macOS Mojave 10.14.3
 - CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
 - Memory: 1.24 GB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 11.12.0 - /usr/local/bin/node
 - Yarn: 1.15.2 - ~/.yarn/bin/yarn
 - npm: 6.7.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - jest-puppeteer: 4.1.1 => 4.1.1
```

**Comment by xiaoyuhen** [comment]
hi @hegelstad 

I am very sorry that we upgraded `wait-on` and caused some issues on your project.

After my tests, this https://github.com/smooth-code/jest-puppeteer/pull/235 PR  will solve this issue.

We will release a new version as soon as possible.
