### ISSUE TITLE
🐛Expect-puppeteer visible options is not available.

### ISSUE THREAD

**Issue by Justinidlerz** [smooth-code/jest-puppeteer#239]
## 🐛 Bug Report

Using typescript and jest-puppeteer v4.1.1.
Cannot use  `visible` options  of  `toMatchElement ` function.

1. The Typescript definition could not update to V4.x.
2. The `visible` options is not available.

## To Reproduce

Create a page add a button then set it `display: none`
Write a test
```
expect(page).toMatchElement("button", { visible: true })
```

## Expected behavior

Throw an error.

## System info

```bash
## System:
 - OS: macOS 10.14.4
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 1.31 GB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.15.3 - /usr/local/bin/node
 - Yarn: 1.15.2 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
```

**Comment by neoziro** [comment]
TypeScript is maintained in https://github.com/DefinitelyTyped/DefinitelyTyped, we don't maintain types here.

**Comment by Justinidlerz** [comment]
@neoziro Ok, But i think it's two bugs, and i have updated the content of the report.

**Comment by lakesare** [comment]
Having the same issue on jest-puppeteer 4.4.0.
`await expect(page).not.toMatchElement('a', { text: 'sepia-fun', visible: true })` does match when this link is hidden (thus breaking the test).
