### ISSUE TITLE
jestPuppeteer.debug() on error?

### ISSUE THREAD

**Issue by FezVrasta** [smooth-code/jest-puppeteer#243]
Hi, I read the documentation and played a lot with jest-puppeteer (love it!).

Something I find myself needing is a way to run `jestPuppeteer.debug()` whenever a test fails for whatever reason, it's very difficult to understand what's going on with a failing test if the browser instantly closes.

I'm quite sure this is possible, but I can't find how to enable it in the docs, may you guys help me out please?

**Comment by neoziro** [comment]
Hello @FezVrasta, I am afraid it is currently not possible using Jest. Anyway if you find a way to do it, please tell us!

**Comment by brbrr** [comment]
FWIW I made it work by redefining the `it` global:

```
global.it = async ( name, func ) => {
	return await test( name, async () => {
		try {
			await func();
		} catch ( error ) {
			if ( E2E_DEBUG ) {
				console.log( error );
				await jestPuppeteer.debug();
			}
			throw error;
		}
	} );
};
```

Also, this is the place where I add any failure-related logging/reporting such as screenshot capture.
