### ISSUE TITLE
How can I restart browser bw test

### ISSUE THREAD

**Issue by alexStrusberg** [smooth-code/jest-puppeteer#244]
I am to run tests on different environments e.g. staging versus production and compare results.
In between a hosts update is required.
Meaning I have o close browser between test and re-open.

How can I close and re-open browser between tests ?

**Comment by neoziro** [comment]
Hello @alexStrusberg, I don't have the answer, but I am sure someone would be able to help you!

**Comment by terryhorowitz** [comment]
To start a browser session before every test I relaunch puppeteer in a beforeEach block before my describe/it blocks
```
let browser, page;

beforeEach(async (done) => {
  browser = await puppeteer.launch();
  page = await browser.newPage();

  done();
});
```

**Comment by terryhorowitz** [comment]
@alexStrusberg To start a browser session before every test I relaunch puppeteer in a beforeEach block before my describe/it blocks
```
let browser, page;

beforeEach(async (done) => {
  browser = await puppeteer.launch();
  page = await browser.newPage();

  done();
});
```

**Comment by UziTech** [comment]
```js
beforeEach(async () => {
  await jestPuppeteer.resetBrowser()
})
```
