### ISSUE TITLE
`Invariant Violation: Invariant Violation`

### ISSUE THREAD

**Issue by FezVrasta** [smooth-code/jest-puppeteer#245]
## 🐛 Bug Report

Most of the times one of my `page.something` actions fail, I get a `Invariant Violation: Invariant Violation` error, paired with the proper "Jest formatted" error (for example, ` No node found for selector: [data-action="blabla"]`)

## To Reproduce

I'm not sure what's the proper way to reproduce it, to me it happens without doing anything more than running `await page.waitForSelector('foobar')` and waiting for the timeout to fail the action.

## Expected behavior

I would expect to see just the `No node found for selector: [data-action="blabla"]` error.

## Link to repl or repo (highly encouraged)

I'll see what I can do to provide one, sorry.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 10.14.4
 - CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
 - Memory: 817.66 MB / 24.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 11.14.0 - /usr/local/bin/node
 - Yarn: 1.15.2 - /usr/local/bin/yarn
 - npm: 6.7.0 - /usr/local/bin/npm
## npmPackages:
 - expect-puppeteer: ^4.1.1 => 4.1.1 
 - jest-puppeteer: ^4.1.1 => 4.1.1 
```

**Comment by neoziro** [comment]
Hello @FezVrasta, writing integration test is hard. Be careful of writing your selector carefully and try to pause your test to see what's going on.

**Comment by FezVrasta** [comment]
Oh, never-mind, it seems to be app specific, sorry for that!
