### ISSUE TITLE
How to disable devtools listener when running puppeteer?

### ISSUE THREAD

**Issue by rodoabad** [smooth-code/jest-puppeteer#248]
I didn't see any documentation on how to disable the devtools listener and prevent it from opening when using `jest-puppeteer`.  Even with `devtools: false` (which I think should affect it) isn't being followed.

**Comment by neoziro** [comment]
Hello @rodoabad, I don't have any answer. I didn't experience that on my side.

**Comment by rodoabad** [comment]
@neoziro when you start up jest with `jest-puppeteer` as a preset it doesn't open a web socket for you?

**Comment by neoziro** [comment]
Yeah it connects to Chrome using Puppeteer and a socket. The code is pretty simple, give a look.
