### ISSUE TITLE
Bring Typescript types into repository

### ISSUE THREAD

**Issue by ifiokjr** [smooth-code/jest-puppeteer#251]
## 🚀 Feature Proposal

Add Typescript types directly to the packages within this repository

## Motivation

This is was discussed in #8 but a lot of has changed since then. 

See the pitch section for more information. In short, jest now uses TypeScript internally and relying on types from a none [`DefinitelyTyped`](https://github.com/DefinitelyTyped/DefinitelyTyped) package is a lot more difficult as it needs types to be made available via [`types-publisher`](https://github.com/microsoft/types-publisher) as well.

## Example

Going forward we would no longer need to add `@types/expect-puppeteer` and `@types/jest-environment-puppeteer`.

## Pitch

I've just opened a DefinitelyTyped [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36073) to export the `PuppeteerEnvironment` default export from `jest-environment-puppeteer` library. The build is currently failing because it relies on none DefinitelyTyped types since Jest now uses typescript directly within its codebase. The potential solution is another [PR](https://github.com/microsoft/types-publisher/pull/622) to the `types-publisher` package but even then I have no way of testing if this solution will work until the PRs are merged.

It seems much simpler to just bring the type definitions into this repo.

**Comment by neoziro** [comment]
Hello @ifiokjr, I don't use TypeScript, that's why adding types to this repository is not a good idea. We need a TypeScript user as maintainer in the project if we want to do so? Are you interested?

**Comment by ifiokjr** [comment]
@neoziro this sounds like something I could help with. I've just sent you an email with a minor question.

**Comment by neoziro** [comment]
@ifiokjr I answered!

**Comment by ifiokjr** [comment]
@neoziro thanks!

I'll create a PR this weekend 😄🤞

**Comment by ifiokjr** [comment]
@neoziro I'll close this for now. It's been a busy few weeks and likely to be especially busy for the next month or so.

**Comment by raphaelsoul** [comment]
type declare wanted
