### ISSUE TITLE
jestPuppeteer.debug support in Jest-circus

### ISSUE THREAD

**Issue by brbrr** [smooth-code/jest-puppeteer#255]
## 💬 Questions and Help

I wonder if there any plans to support jest-circus. While `jest-circus` works kinda fine out of the box, I noticed that `jestPuppeteer.debug()` does not really work as expected.

I have this `CustomEnvironemnt` class that should stop the execution on test failure:

```
const PuppeteerEnvironment = require( 'jest-environment-puppeteer' );

class CustomEnvironemnt extends PuppeteerEnvironment {
	async handleTestEvent( event ) {
		if ( event.name === 'test_fn_failure' ) {
			await this.global.jestPuppeteer.debug();
		}
	}
}
```

It does trigger the chrome's debugger, but unfortunately, after resuming the debugger - browser just closes itself.

**Comment by neoziro** [comment]
Hello @brbrr, yeah `jestPuppeteer.debug()` is kind of hacky and we should remove it. The only problem here is that we don't have any correct way to set the timeout of the fly to actually "pause" a test in Jest.

**Comment by brbrr** [comment]
make sense. What would you recommend as an alternative? I wonder if we can use some sort of `DEBUG` env variable to setup jest timeouts, and run the debugger on test failure or on-demand (similar to `jestPuppeteer.debug()`)

**Comment by neoziro** [comment]
Hello yes maybe it would be a good solution but no very user-friendly.

**Comment by sergtimosh** [comment]
Have you tried to add adding freak timeout as test argument?(I'm not using custom environment, just add jestPuppeteer.debug() to each test while test development)
It is the only way I can use debug
Just like this:
``` lang-js

jest.retryTimes(3)

describe('Test', () => {
    test('Test_1', async () => {
        await jestPuppeteer.resetBrowser()
        await loginPage.login()
        await jestPuppeteer.debug() //paused in browser, and after resuming in browser stays paused in test runner
        await loginPageAssert.isLoggedIn()
    }, 999999) //timeout

})
```

**Comment by MatthiasEngh** [comment]
This question is asked all over the place. The timeout https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js#L42 is probably ignored due to the same reason as https://github.com/facebook/jest/issues/9359. You can use --testtimeoutnumber to test: https://jestjs.io/docs/en/cli#--testtimeoutnumber
