### ISSUE TITLE
Running individual tests locally passes, running entire test suite via Jenkins CI causes multiple failures

### ISSUE THREAD

**Issue by AdamBD** [smooth-code/jest-puppeteer#266]
Hello,

I am hoping to get some advice for how to best run jest-puppeteer on Jenkins-CLI

1. We have around 12 test files, each file has around 2-3 tests within for different pages on our site.
2. When individually running each file on its own, all the tests within pass.
3. However when running via Jenkins-CI we run the following jest command to run all tests at once: 

`jest -c jest.config.js --verbose --runInBand --forceExit --detectOpenHandles`

Now we start to see tons of tests failing.

Are there considerations we need to make when letting jest run it its normal mode which is running multiple test files at the same time?

**Comment by neoziro** [comment]
Hello @AdamBD, I think your tests are not isolated. Are you sure to reset the database between each test?

**Comment by AdamBD** [comment]
@neoziro - Yes after each test we are clearing everything. Also each tests creates unique DB entries as to have no conflicts with prior tests. 

When running locally the `--runInBand` works well, but we suspect that maybe in Jenkins this is not the case, as when we run locally _without_ `--runInBand` we also have failures. 

It seems puppeteer (at least with our tests) has issues when running a few parallel tests

**Comment by santaclauze** [comment]
Any news on this? we have a similar issue.

About 100 tests in 20 different files. Tests will pass locally but the CI gives random results. All tests may pass a couple of times but then some tests will start failing randomly.

We are using `waitForSelector`, `waitForNavigation` as much as we can, use a number of time outs and `--runInBand` but we still encounter these issues that seem to be racing problems.

**Comment by neoziro** [comment]
@santaclauze integration testing is hard. Issues could be cause by pending request that are running when a new test start. I don't have out of the box solution, you have to iterate on it..

**Comment by neoziro** [comment]
We will not fix it in this library since it is a biggest problem that can't be solved here.
