### ISSUE TITLE
Allow configuring puppeteer via code

### ISSUE THREAD

**Issue by Swatinem** [smooth-code/jest-puppeteer#268]
## 🚀 Feature Proposal

It would be nice if I could add puppeteer launch options via other mechanisms than `jest-puppeteer.config.js`.

For example there is `testEnvironmentOptions` in the jest config, and other plugins may also use `globals` for this.

See:
https://jestjs.io/docs/en/configuration#testenvironmentoptions-object
https://kulshekhar.github.io/ts-jest/user/config/#introduction

## Motivation

I don’t want to have to put things into a `jest-puppeteer.config.js` when I can just as well use the normal jest config mechanisms. The less separate files I have to maintain, the happier I am :-)

## Example

```ts
testEnvironmentOptions: {
  launch: { headless: false },
},
```

## Pitch

Well obviously, its all about configuring the environment :-)

**Comment by neoziro** [comment]
We don't have access to `testEnvironmentOptions` in globalSetup, sorry not possible.
