### ISSUE TITLE
Wait for server command

### ISSUE THREAD

**Issue by Diokuz** [smooth-code/jest-puppeteer#27]
My `jest-puppeteer.config.js` is

```js
module.exports = {
  server: {
    command: 'node puppeteer/server-storybook.js',
  },
...
```

And sometimes I have a network error: tests are trying to reach node process, which is launching, but not completely launched.

Is it possible to tell `jest-puppeteer` wait until `ping localhost:3000` will be ok? Or, at least, tell to wait some amount of milliseconds.

Now I have to set `await sleep(1000)` before each test suit, which is not convenient.

The problem could be critical in case if you are launching something heavy like `webpack-dev-server`.

**Comment by neoziro** [comment]
It is already possible using `port` option. See https://github.com/smooth-code/jest-puppeteer#jest-puppeteerconfigjs

I use it in all my projects:

```js
module.exports = {
  launch: {
    headless: process.env.HEADLESS !== 'false',
  },
  server: {
    command: 'yarn babel-node src/server/main.js',
    port: 4444,
  },
}
```
