### ISSUE TITLE
`@types/expect-puppeteer` `toMatch` interferes with builtin matcher

### ISSUE THREAD

**Issue by Swatinem** [smooth-code/jest-puppeteer#271]
ll

## 🐛 Bug Report

Jest already has a `toMatch` matcher, which is synchronous.
However, `expect-puppeteer` overrides that one and makes it async.
This can be confusing when mixing tests that are run in node and tests that are run via puppeteer in the same repository.

## To Reproduce

* have a pre-existing project which uses `expect(X).toMatch(Y)`
* install `@types/expect-jest`
* Notice that you get tons of `ERROR: (no-floating-promises) …/__tests__/assertions.ts[135, 5]: Promises must be handled appropriately` errors…

## Expected behavior

Don’t override / monkeypatch existing `expect` methods in non-obvious ways :-)

**Comment by neoziro** [comment]
Hello @Swatinem, I know it could be a problem with TypeScript. However it is not a bug, but just a miss typing. In next version we will probably rename it to avoid these kind of problems.
