### ISSUE TITLE
`toSelect` fails when using custom `Page` instance

### ISSUE THREAD

**Issue by Swatinem** [smooth-code/jest-puppeteer#272]
## 🐛 Bug Report

When using a custom `Page` instance, for example using `browser.newPage()`, the `toSelect` matcher fails with the following Error:
`JSHandles can be evaluated only in the context they were created!`

## To Reproduce

NOTE: I haven’t run this inside a *reduced* testcase, but my testsuite runs correctly when *not* using `browser.newPage()`.

```ts
// fails:
const p = await browser.newPage()
// works:
// const p = page
await expect(p).toSelect('select[name="fontFamily"]', font)
```

## Expected behavior

This should work no matter which `page` instance it is run on.

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

* node@10.15.3
* jest-puppeteer@4.3.0
* expect-puppeteer@4.3.0

**Comment by Mavrin** [comment]
Look like I fix it https://github.com/smooth-code/jest-puppeteer/pull/275
