### ISSUE TITLE
Running in parallel in Selenoid

### ISSUE THREAD

**Issue by test-pilott** [smooth-code/jest-puppeteer#279]
I've been trying to setup jest-puppeteer to create and connect to Chrome instances running in Selenoid, however the test runs are pretty flaky when I am running the tests in parallel (--maxWorkers=3). 

I noticed that sometimes the sessions are not cleared, even though I close the browser properly after each suite. 

Is global.browser shared between workers? Has anyone succeeded in using Selenoid in parallel?

Note that before connecting to a Selenoid browser, we need to do a POST to create a session.

Thanks.

**Comment by pavoltravnik** [comment]
global.browser is shared among all tests. 
You are looking for option https://github.com/smooth-code/jest-puppeteer#configure-puppeteer
`browserContext: 'incognito',`

**Comment by sergtimosh** [comment]
> global.browser is shared among all tests.
> You are looking for option https://github.com/smooth-code/jest-puppeteer#configure-puppeteer
> `browserContext: 'incognito',`

I've tried to set launch option browserContext: 'incognito' with maxWorkers = 2 or more and still all this test start in one browser context. What am I doing wrong?
My jest-puppeteer.config.js setup:
```js
case 'darwin':
        module.exports = {
            launch:
                process.env.DEBUG ? {
                    browserContext: 'incognito',
                    headless: false,
                    devtools: true,
                    args: DARWIN_ARGS,
                    defaultViewport: {
                        width: 1600,
                        height: 720
                    },`
