### ISSUE TITLE
Use preset only on some files

### ISSUE THREAD

**Issue by georgjaehnig** [smooth-code/jest-puppeteer#282]
Hi, I couldn't find the info in the docs or the issues.

Until now I've only had in my project one test file with integration tests called `calls.test.js`. Every test required Chrome so having `"preset": "jest-puppeteer"` was a good solution.

Now I want to add unit tests in `env.test.js`, and I want to be able to run it separately from `calls.test.js`. However, even `npm run test env.test` always also loads the browser right now, no wonder with that `preset`.

Is there a way to apply `"preset": "jest-puppeteer"` only when certain files (in my case `calls.test.js`) are run?

**Comment by neoziro** [comment]
Hello @georgjaehnig, the best option to do it actually is to have two separated Jest configs and point one or the other. https://jestjs.io/docs/en/cli#config-path

**Comment by georgjaehnig** [comment]
Thank you, that works!
