### ISSUE TITLE
Supporting puppeteer 2.0

### ISSUE THREAD

**Issue by paperbd** [smooth-code/jest-puppeteer#291]
## 🚀 Feature Proposal

Support a peer dependency of Puppeteer 2.0 rather than requiring a 1.x version

## Motivation

We depend on this package for our tests, and we'd like to run them on macOS Catalina, but we've had issues with the version of chromium necessary for these tests, on Catalina. Puppeteer 2.0 supports a newer version of chromium that should support Catalina better.

## Example

We would use this to run the functional tests for a project I work on.

## Pitch

Supporting the latest browsers will keep this package relevant! :)

**Comment by ryanjwilke** [comment]
I agree. I've already upgraded to using puppeteer 2.0, but I keep getting this warning:
```
warning " > jest-puppeteer@4.3.0" has incorrect peer dependency "puppeteer@^1.5.0"
```

**Comment by colinrotherham** [comment]
@paperbd @ryanjwilke Yeah look in `package.json` only **^1.5.0** is supported:

```
"peerDependencies": {
  "puppeteer": "^1.5.0"
},
```

I've opened a pull request to fix it here: https://github.com/smooth-code/jest-puppeteer/pull/289

**Comment by ryanjwilke** [comment]
@colinrotherham Thanks. No rush for me really. All my tests still work just fine with `2.0` :)

Thanks for working on a fix for us all already.

**Comment by paperbd** [comment]
Looks like https://github.com/smooth-code/jest-puppeteer/pull/289 is merged now, so I'll close this. Thanks so much @colinrotherham!
