### ISSUE TITLE
How to make `window/document` available?

### ISSUE THREAD

**Issue by FezVrasta** [smooth-code/jest-puppeteer#295]
I'd like to use jest-puppeteer pretty much like Jest + JSDOM, I will not test real web pages, but I need the real DOM APIs to test some code.

I would like to have access to `window` and/or `document` globally, how can I do?

This is my Jest config:

```json
  "jest": {
    "preset": "jest-puppeteer",
    "testMatch": ["**/src/**/*.test.js"],
    "globalSetup": "jest-environment-puppeteer/setup",
    "globalTeardown": "jest-environment-puppeteer/teardown",
    "testEnvironment": "jest-environment-puppeteer"
  },
```

Here's an example of a test I'm trying to run:

```js
it('returns a parent element', () => {
  const child = document.createElement('div');
  const parent = document.createElement('div');
  parent.appendChild(child);

  expect(getParentNode(child)).toBe(parent);
});
```

**Comment by goliney** [comment]
I also wonder if such a thing is possible.

**Comment by dcoollx** [comment]
Unfortunately this is not a possibility due to the limitations of puppeteer. You can however run this script within the window context 
```
it('test',()=>{
  page.evaluate(()=>{
  //you have access to window obj here
   const child = document.createElement('div');
  const parent = document.createElement('div');
  parent.appendChild(child);
  });
//to check if there is a parent child relationship
let child = await page.$('parent child');//selector will return null if it doesnt exist
expect(child).toBeTruthy();
})
```

**Comment by igorpupkinable** [comment]
This affects integration with Percy as it needs access to `window`.
I had to wrap @percy/puppeteer `percySnapshot` method with evaluate as follows:
```
export const takeSnapshot = (name: string) => page.evaluate(
  (n) => percySnapshot(page, n),
  name,
);
```

**Comment by igorpupkinable** [comment]
This an issue because `@percy/puppeteer` package stopped working as it references `window` to do its stuff.
The suggestion above does not work.
```
page.evaluate(() => {
  console.debug('window', window); // Throws window not defined error.
});
```
