### ISSUE TITLE
Consider moving config to jest config?

### ISSUE THREAD

**Issue by timwis** [smooth-code/jest-puppeteer#30]
Just an idea, not sure how feasible it is, but it would be great if I could just put my `headless` configuration inside my `jest.config.js` file instead of creating a new config file just for that.

However, totally worth it to use this preset!

**Comment by neoziro** [comment]
Wait and see https://github.com/facebook/jest/issues/5957

**Comment by srounce** [comment]
facebook/jest#6486 was merged on June 20th.

**Comment by neoziro** [comment]
Yes it is! Time to work on it!

**Comment by neoziro** [comment]
See #111
