### ISSUE TITLE
Request is already handled!

### ISSUE THREAD

**Issue by rodoabad** [smooth-code/jest-puppeteer#308]
#Note: Reposting this from https://github.com/smooth-code/jest-puppeteer/issues/147 since we'd like this issue to be opened again.

# Error Information
Request is already handled!

# To Reproduce
```
describe('Test', () => {
    beforeEach(async () => {
        jest.setTimeout = 30000;
        await page.setRequestInterception(true);
        page.on('request', request => {
            request.continue();
        })
        await page.goto('https://www.google.com/');
    });

    afterEach(async () => {
        page.removeListener("request", () => {});
    })

    it('case1:...', async () => {
        await expect(page).toMatch('Google');
    })

    it('case2:...', async () => {
        await expect(page).toMatch('Google');
    })

});
```
# Expected behavior
I want to modify some response data in every testcase, so help me plz.

**Comment by rodoabad** [comment]
Current fix is...

```
beforeEach(async () => {
        jest.setTimeout = 30000;
        page = await browser.newPage();
        await page.setRequestInterception(true);
        page.on('request', request => {
            request.continue();
        })
        await page.goto('https://www.google.com/');
    });
```

However we'd like to avoid having to do `await browser.newPage()` every time.

**Comment by counterbeing** [comment]
I've managed to get around this by using `resetPage`:

```
  beforeEach(async () => {
    await jestPuppeteer.resetPage();
    await page.goto('http://localhost:5001');
  });
```

I don't know if it makes a difference with your case but i'm using the jest command line option `--runInBand`.

**Comment by rodoabad** [comment]
@counterbeing I'll try and use this and report back.

**Comment by rodoabad** [comment]
> I've managed to get around this by using `resetPage`:
> 
> ```
>   beforeEach(async () => {
>     await jestPuppeteer.resetPage();
>     await page.goto('http://localhost:5001');
>   });
> ```
> 
> I don't know if it makes a difference with your case but i'm using the jest command line option `--runInBand`.

Just wondering where did `jestPuppeteer` come from?

**Comment by UziTech** [comment]
Jest puppeteer adds it
