### ISSUE TITLE
Support for Playwright?

### ISSUE THREAD

**Issue by FezVrasta** [smooth-code/jest-puppeteer#309]
## 🚀 Feature Proposal

The guys behind Puppeteer just released Playwright, it would be great to support it in Jest.

https://github.com/microsoft/playwright

## Motivation

It looks like Playwright is the successor of Puppeteer, with more browser support and a better API.

## Example

N/A

## Pitch

jest-puppeteer already has a good foundation to support Playwright.

**Comment by suzil** [comment]
This repo is new: https://github.com/mmarkelov/jest-playwright

**Comment by hashseed** [comment]
For clarification: we (Chrome DevTools team) are continuing to maintain Puppeteer. We are pursuing some plans to improve its usability. So I would not say that Puppeteer has a successor.

**Comment by FezVrasta** [comment]
@hashseed I suppose all the improvements to Puppeteer will get merged on Playwright-chrome though?

**Comment by hashseed** [comment]
That's unclear to me unfortunately. Playwright is developed and maintained by another team and we don't have insight into their plans.
