### ISSUE TITLE
Puppeteer in headless mode takes empty screenshot of Canvas element on first render.

### ISSUE THREAD

**Issue by anurasin** [smooth-code/jest-puppeteer#310]
## 🐛 Bug Report

Puppeteer in headless mode is not able to take the screenshot of a canvas element in my test app. Though while using puppeteer in non-headless mode, it's working perfectly fine.

**This is my test scenario,** 
1. Press some button, it will invoke WebGL rendering on the canvas element.
  (As soon as the rendering is finished source code update a div element value on the web page.)
2. Test code wait for the div element value to get changed
3. Take the screenshot of canvas element.
4. Repeat step 1-3 for some 'n' number of times (each time code will render something on the canvas)

On taking the screenshot, I see that sometimes the first screenshot if blank other times second. It's showing intermittent behavior. It's working fine with headful mode though.

## To Reproduce

// My function to take a screenshot
async function captureScreenshotAndCompare(element: ElementHandle, fileName: string, shouldCompare: boolean = true) {
  const testFile = Path.resolve(testFolder, `${fileName}.png`);

  // capture screenshot
  const image = await element.screenshot({ path: testFile });

  // compare with baseline
  if(!shouldCompare) return;

  expect(image).toMatchImageSnapshot({
    failureThreshold: 0.1,
    failureThresholdType: 'percent',
    customSnapshotsDir: baselineFolder,
    customDiffConfig: { threshold: 0.1 },
    customSnapshotIdentifier: () => {
      return fileName;
    },
  });
}

const canvas = await page.$('canvas[id="webgl-canvas"]');
expect(canvas).not.toBeNull();
if(!canvas) return;

await captureScreenshotAndCompare(canvas, 'Image_1', true);
let index: number = 2;

while (index <= maxCount) {
      // move to next step
      await nextBtn.click();
      await page.waitFor(() => document.querySelector('#eventName')!.innerHTML === "rendered" );
      await captureScreenshotAndCompare(canvas, `Image_${index}`);
      index += 1;
}

## Expected behavior
Screenshot should be correct both in headless and headful mode.

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

**These are all the versions exist in my package.json file.**
"puppeteer": "^2.0.0",
"jest-puppeteer": "4.3.0",
"jest-image-snapshot": "2.11.0"
"@types/puppeteer": "^1.19.1",
"@types/jest-environment-puppeteer": "4.3.1",
"@types/expect-puppeteer": "3.3.1",

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash

```

**Comment by ramyhhh** [comment]
I got the same issue with pdf

**Comment by ShivamJoker** [comment]
Same here

**Comment by UziTech** [comment]
This sounds like an issue that should be reported to the [puppeteer](https://github.com/puppeteer/puppeteer) repo.
