### ISSUE TITLE
Access IndexedDB from window

### ISSUE THREAD

**Issue by SilvanTheuma** [smooth-code/jest-puppeteer#311]
Hi,

I'm trying to access indexedDB from the window object, however I keep getting the below error.

`DOMException: Failed to execute 'open' on 'IDBFactory': access to the Indexed Database API is denied in this context.`

This is how I am trying to do it.

```
await page.evaluate(() => {
    const idb = window.indexedDB.open("databaseName");
});
```

I also set `--allow-file-access-from-files` as part of the args in the `jest-puppeteer.config.js` and set the `browserContext: 'default'`

Still I cannot get it to work! Does anyone have the same problem?

**Comment by gregberge** [comment]
I think it is a Puppeteer bug and not related to jest-puppeteer at all isn't it?

**Comment by SilvanTheuma** [comment]
I'm not sure. I'm using jest-puppeteer, that's why I posted here. So do you think this regards puppeteer directly?

**Comment by gregberge** [comment]
Yeah I think so.

**Comment by andreisaikouski** [comment]
@SilvanTheuma did you find a workaround to this?

**Comment by jonab12** [comment]
@andreisaikouski Have some JS code OUTSIDE of Puppeteer execute the IDB commands that runs parallel to Puppeteer. Keep that code on the DEV env only
