### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by kytwb** [smooth-code/jest-puppeteer#32]
Somehow our e2e tests suite stopped working and I couldn't figure out why. The **toMatch()** method was always throwing `Text not found` when in fact the error catched in [here](https://github.com/smooth-code/jest-puppeteer/blob/ec6adcd8965eda64729a5b6e57806384e56a4b18/packages/expect-puppeteer/src/matchers/toMatch.js#L19) was due to an update of our server CSP:

> Error: Evaluation failed: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".

**Comment by neoziro** [comment]
Described in #33
