### ISSUE TITLE
Errors "between" tests cause incorrect snapshot names

### ISSUE THREAD

**Issue by l-abels** [smooth-code/jest-puppeteer#323]
## 🐛 Bug Report

In a suite of `async` tests, sometimes errors can occur within the browser at the very start of the next test.  The test fails but continues running.  This causes the tests to run interleaved, interfering with global snapshot state. 

When I run three passing tests, the execution order looks like this:
```
Test 1 begins
Test 1 awaits
Test 1 resumes
Test 1 takes snapshot

Test 2 begins
Test 2 awaits
Test 2 resumes
Test 2 takes snapshot

Test 3 begins
Test 3 awaits
Test 3 resumes
Test 3 takes snapshot
```
When the issue occurs, the order looks like this:

```
Test 1 begins
Test 1 awaits
Test 1 resumes
Test 1 takes snapshot

Test 2 begins and immediately suffers an error
Test 2 awaits

Test 3 begins
Test 3 awaits

Test 2 resumes
Test 2 takes snapshot with the wrong name

Test 3 resumes
Test 3 takes snapshot with the correct name, but an index of 2
```

 The result is that my snapshot file looks like this, with one test using an incorrect snapshot name:

```
exports[`Profile Page Matches the Screenshot 1`] = `2`;

exports[`Profile Page Matches the Screenshot 2`] = `3`;

exports[`User Management Page Matches the Screenshot 1`] = `1`;
```

As a workaround, I can use
```
afterEach(async () => {
    await jestPuppeteer.resetPage()
});
```
to prevent the error from occurring.

## To Reproduce

This is difficult, since it relies on errors occurring in the website I'm testing.  I have three simple tests in one file:

```
describe('User Management Page', () => {
    it('Matches the Screenshot', async () => {
         await page.goto('http://localhost:8081/settings/user-management');
         const image = await page.screenshot();

          expect(1).toMatchSnapshot();
    });
});
describe('Application Management Page', () => {
    it('Matches the Screenshot', async () => {
         await page.goto('http://localhost:8081/settings/application-management');
         const image = await page.screenshot();

          expect(2).toMatchSnapshot();
    });
});
describe('Profile Page', () => {
    it('Matches the Screenshot', async () => {
         await page.goto('http://localhost:8081/profile');
         const image = await page.screenshot();

          expect(3).toMatchSnapshot();
    });
});

```

The error occurs in the User Management page's javascript, but is actually thrown on the line ` it('Matches the Screenshot', async () => {` in the **next** `describe` block.  The test continues executing, and takes a snapshot.

## Expected behavior

Either of the following seems reasonable:

1. The error should not cause the test to fail, as it's not actually occurring in the context of the test itself.

2. The error should cause the test to exit, like it would if it occurred in the body of the test.

**Comment by gregberge** [comment]
It is your responsibility to make each test unitary. You could have the same problem by using the same set of data. Your workaround is good, but I don't think it should be part of this repository.

**Comment by l-abels** [comment]
@gregberge Sorry for the late followup, but I'm not sure this is an issue with how I've structured my tests.  From what I've read about Jest, `async/await` tests should "just work" and it shouldn't be so easy to make them run interleaved like this.

Here's a snippet from the output of my tests:

```
  * Application Management Page › Matches the Screenshot

    //rest of this error omitted
      at http:/localhost:8081/assets/vendors.chunk.js:40083:26
      at Suite.<anonymous> (pages.test.js:78:5)

  * Profile Page › Matches the Screenshot

    Protocol error (Target.activateTarget): Session closed. Most likely the page has been closed.

      80 |          await page.goto('http://localhost:8081/settings/application-management');
      81 |          
    > 82 |          const image = await page.screenshot();
         |                                   ^
      83 | 
      84 |          expect(image).toMatchImageSnapshot();
      85 |     });

      at CDPSession.send (node_modules/puppeteer/lib/Connection.js:180:29)
      at Page._screenshotTask (node_modules/puppeteer/lib/Page.js:926:24)
        -- ASYNC --
      at Page.screenshot (node_modules/puppeteer/lib/helper.js:111:15)
      at Object.<anonymous> (pages.test.js:82:35) <---This line is in the previous test!
```

According to this, the second test is somehow failing in the body of the previous test.  I'm trying to understand how it's possible that a test can suffer an error and fail yet still continue execution as if it hadn't.  Furthermore, if this test is going to continue to execute why does it update the global state to show that the next test is running?  

I'm not doing anything fancy here with configuration and these tests only contain basic methods from `jest` and `puppeteer`.  It seems like this issue could occur when testing any website.

**Comment by gregberge** [comment]
If it is relative to execution order, it is a Jest issue.
