### ISSUE TITLE
Getting "browser.disconnect is not a function at PuppeteerEnvironment.teardown"

### ISSUE THREAD

**Issue by Pomax** [smooth-code/jest-puppeteer#325]
## 🐛 Bug Report

I'm using jest 24.9.0 with jest-puppeteer 4.4.0 and puppeteer 2.1.1, and am getting this error when trying to end my test:

```bash
 FAIL  test/webclient.test.js
  ● Test suite failed to run

    TypeError: browser.disconnect is not a function

      at PuppeteerEnvironment.teardown (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:170:21)
```

## To Reproduce

I'm using the simplest of jest configs in package.json:
```json

  "jest": {
    "preset": "jest-puppeteer"
  },
```

And have the following test:

```js
const path = require(`path`);
const fetch = require(`node-fetch`);
const { generateClientServer } = require(`../src/generate-client-server.js`);

describe("web client tests", () => {
  let webclient;

  it("should support all publically documented properties and functions", async (done) => {
    class WebClientClass {
      async onConnect() {
        await page.goto(`http://localhost:${webclient.address().port}`);
        await page.click('#quit');
      }
      async "test:set"(value) {
        this.value = value;
      }
    }

    class ServerClass {
      onDisconnect(client) {
        this.quit();
      }
      async onQuit() {
        await browser.close();
        done();
      }
      async "test:receive"(client) {
        client.test.set('test');
      }
    }

    const ClientServer = generateClientServer(WebClientClass, ServerClass);
    const server = ClientServer.createServer();
    server.listen(0, () => {
      webclient = ClientServer.createWebClient(
        `http://localhost:${server.address().port}`,
        path.join(__dirname, `public-test`)
      );
      webclient.listen(0);
    });
  });
});
```

I'm testing a socket based `server <-> client <-> browser` chain, where the flow is:
- server stands up, starts listening on "some port" for websocket requests, and creates a client
- client stands up, creates a socket connection to the server, creates its own plain web server,
- puppeteer is told to visit that client's web address and load the associated page, which looks like:

```html
<script src="socketless.js"></script>
<script src="ui.js" type="module" async></script>
<script src="start.js" type="module" async defer></script>
<div id="div"></div>
<button id="quit">quit</button>
```

that quit button sends a signal to the client to disconnect itself from the server, so we end up in the server's `onDisconnect`, which makes the server itself quit. As part of its teardown, it calls `onQuit`, and that tries to gracefully close the puppeteer browser and then tell jest that we're done.

All of which works splendidly, except for the part where `browser.close()` causes the type error mentioned above, and just goes "whoa there buddy, that's a big fat error"

## Link to repl or repo (highly encouraged)

repo/branch: https://github.com/Pomax/socketless/commit/ba1b805ab14d5b0651a14285915fa963e006717d

steps to reproduce:

```bash
git clone https://github.com/Pomax/socketless
cd socketless
git checkout ba1b805ab14d5b0651a14285915fa963e006717d
npm install
npm test
```

## Run `npx ......`

```bash
*** Clipboard option removed - use clipboardy or clipboard-cli directly ***
```

So you probably want to fix that. With that said, you also probably wanted to see this, instead:

```bash
## System:
 - OS: Windows 10 10.0.17134
 - CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
 - Memory: 51.98 GB / 63.88 GB
## Binaries:
 - Node: 12.12.0 - C:\Program Files\nodejs\node.EXE
 - npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - jest-puppeteer: ^4.4.0 => 4.4.0
```

(Yes, this machine has 64GB of ram. Yes, I've run out before...)

**Comment by Pomax** [comment]
Logging `browser` in `node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js`, near line 170, shows that it is in fact nothing like the browser that puppeteer expects, and instead is logging something that looks suspiciously identical to my `server` variable. How is `jest-puppeteer` ensuring that the `browser` it go from Puppeteer gets cleanly injected into a test?

**Comment by UziTech** [comment]
is this still an issue with the latest version of puppeteer?

**Comment by Pomax** [comment]
Apologies for not responding: github never even notified me of your April 9th message. I haven't worked on the project this came out of for a while, but I might be able to test this or next weekend.
