### ISSUE TITLE
Run tests using both chrome and firefox in a single run using `jest-puppeteer` module.

### ISSUE THREAD

**Issue by maurusrv** [smooth-code/jest-puppeteer#329]
Hi, is there a way to run my tests using `jest-puppeteer` that will test both in chrome and firefox? 

I wonder if there's a way to integrate `puppeteer-firefox` in either `jest.setup.js` or `jest.config.js` or `jest-puppeteer.config.js`.

Even just an idea or direction will be very much appreciated. 

Thank you!

**Comment by Gbahdeyboh** [comment]
Do you mean you want to be able to run tests in firefox apart from the default chromium-browser using the default jest puppeteer setup?

You need to be more explicit with your Question...

**Comment by maurusrv** [comment]
what i wanted to do is test both on chrome and firefox on a single test run. That is: when i run `npm test`, i would be using the chromium-browser first, then firefox next, just by using a `browser` variable to switch and instantiate a browser object that can be used by my test file.

That after my test `PASS` or `FAIL`, i've run my test through chrome and firefox. 

Or is the only way would be just change my config to use the default setup then, change my config to use `puppeteer-firefox` and run my test again?

my end goal is to automate my test both in chrome and firefox so that i can integrate it in my production building phase.

Thank you for entertaining my question!

**Comment by Gbahdeyboh** [comment]
The default implementation only allows you to manually change from `puppeteer` to `puppeteer-firefox`. Which means you will have to run each test one after the other. 

What do you want to achieve by trying to do this?

I would like you to note that depending on what is been tested, some tests that pass on chrome might fail on firefox and vice versa. 

A workaround would be to create 2 separate folders, one for chrome tests and another for puppeteer tests. Each folder having its own config file. Then you run one test after the other.

**Comment by maurusrv** [comment]
> What do you want to achieve by trying to do this?

Maybe i'm just overthinking my development process while in fact, it can really be simple. 

> I would like you to note that depending on what is been tested, some tests that pass on chrome might fail on firefox and vice versa.

now i get it. 2 folders. yes. i guess, i just need to create a separate script in my `package.json` for both chrome test and firefox test and i can combine it in a single script too if i want that "single test run" scenario. 

Thanks.
