### ISSUE TITLE
Show original error message

### ISSUE THREAD

**Issue by neoziro** [smooth-code/jest-puppeteer#33]
As mentioned in #32, error messages are swallowed by several matchers:

- [notToMatch](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer/src/matchers/notToMatch.js)
- [notToMatchElement](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer/src/matchers/notToMatchElement.js)
- [toMatch](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer/src/matchers/toMatch.js)
- [toMatchElement](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer/src/matchers/toMatchElement.js)

The goal is to create an helper that keep original error message additionally to the matcher error message.

**Comment by kytwb** [comment]
@neoziro do you have an idea in mind? I can implement it and come up with a PR.

**Comment by neoziro** [comment]
Yeah, if you understand the goal, you are welcome!
