### ISSUE TITLE
Why is "window" not defined? The tests are running in Chrome.

### ISSUE THREAD

**Issue by Domvel** [smooth-code/jest-puppeteer#333]
# 💬 Questions and Help

Why is `window` not defined? The tests are running in Chrome. But `global` (node) is defined. If I set the `headless` config to false, I see Chrome. (Headless is set to true by default.) 

**test.spec.ts**
```ts
test('two plus two is four', () => {
  console.log(typeof window, typeof global);
  expect(2 + 2).toBe(4);
});
// Result: undefined, object
```

**jest-config.js**

```js
module.exports = {
  preset: 'jest-puppeteer',
  // preset: 'jest-preset-angular',
  roots: ['src'],
  setupFilesAfterEnv: ['<rootDir>/src/jest-setup.ts'],
  moduleDirectories: ['node_modules', 'src'],
  verbose: true,
  transform: {
    '^.+\\.(ts|js|html)$': 'ts-jest'
  },
  moduleNameMapper: {
    '@app/(.*)': '<rootDir>/src/app/$1',
    '@assets/(.*)': '<rootDir>/src/assets/$1',
    '@core/(.*)': '<rootDir>/src/app/core/$1',
    '@env': '<rootDir>/src/environments/environment',
    '@src/(.*)': '<rootDir>/src/src/$1',
    '@state/(.*)': '<rootDir>/src/app/state/$1'
  },
  transformIgnorePatterns: ['/node_modules/(?!@ionic|ngx-socket-io/).+\\.js$']
};
```

**Version**
    "puppeteer": "^2.1.1",
    "jest-puppeteer": "^4.4.0",
    "jest-preset-angular": "^8.1.2",
    "jest": "^25.1.0",
    "ts-jest": "^25.2.1",

I though with puppeteer I can run my tests in a Browser enviroment instead of the fake jsdom with has missing features like `Object#values`, etc.

**Comment by gregberge** [comment]
Tests are running in Node. You can access window threw Puppeteer.

**Comment by jarodsmk** [comment]
@Domvel I see you're trying to get puppeteer to work with Angular & Jest, did you ever come right?
