### ISSUE TITLE
Parallel test by directory/session (prelogin and postlogin)

### ISSUE THREAD

**Issue by rainercedric23** [smooth-code/jest-puppeteer#336]
## 🚀 Feature Proposal

To have a parallel test grouped by directory (once one directory with paralled test is done it will test the next directory all together), this would be helpful in case of prelogin, authentication and post login test pages since session during test is shared among all test suites.

## Motivation

Currently, we're running our test suites with `--runInBand` option to avoid session issues, ie. authentication with post login pages running in parallel would have a race condition. in this case we have 20+ e2e test running sequentially which isn't productive since it takes 3-4 minutes considering it would have more test coming with new features

## Example

this would be useful with tests having a asynchronous and synchonous test running so it hasten up the running of test all together with sites having a prelogin and post login pages.

    /test/prelogin/*.test.ts
    /test/authentication/*.test.ts
    /test/postlogin/*.test.ts
    // more test directory that will run asynchronously

**Comment by UziTech** [comment]
You can already use projects config in jest for this
