### ISSUE TITLE
TypeScript typings: Property 'blur' does not exist on type 'Element'.

### ISSUE THREAD

**Issue by jasonharrison** [smooth-code/jest-puppeteer#339]
## 🐛 Bug Report

Element.blur() is not defined in the TypeScript definition

## To Reproduce

```typescript
  await page.goto(baseURL + '/');
  page.$eval('input[id=email]', (e) => e.blur()); // Property 'blur' does not exist on type 'Element'.
  page.$eval('input[id=email]', (e) => (e as any).blur()); // Works fine
```

## Expected behavior

.blur() should be defined in types.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

```bash
## System:
 - OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
 - CPU: (4) x64 Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
 - Memory: 1.18 GB / 7.78 GB
 - Container: Yes
 - Shell: 3.0.2 - /usr/bin/fish
## Binaries:
 - Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
 - Yarn: 1.22.4 - ~/.yarn/bin/yarn
 - npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
## npmPackages:
 - jest-puppeteer: ^4.4.0 => 4.4.0 

```

**Comment by johnneuland** [comment]
I am trying to pass a ref property into a custom FieldInput component where I use Input from Native Base. 
```
const fieldRef = useRef<Input>(null);
...
 fieldRef.current?.blur();
```
I get the same error here: ```Property 'blur' does not exist on type 'Input'.```
How can I resolve it in this case? @KashubaK
