### ISSUE TITLE
wait-on 4.4.0

### ISSUE THREAD

**Issue by thernstig** [smooth-code/jest-puppeteer#340]
According to https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-dev-server/package.json version `4.4.0` contains `wait-on ^4.0.0`. How is it that when I install jest-dev-server my package.lock looks like this?

```json
    "jest-dev-server": {
      "version": "4.4.0",
      "resolved": "https://arm.sero.gic.ericsson.se/artifactory/api/npm/npm-remote/jest-dev-server/-/jest-dev-server-4.4.0.tgz",
      "integrity": "sha1-VXET+q4od0UhYmlqqUweREkasBE=",
      "dev": true,
      "requires": {
        "chalk": "^3.0.0",
        "cwd": "^0.10.0",
        "find-process": "^1.4.3",
        "prompts": "^2.3.0",
        "spawnd": "^4.4.0",
        "tree-kill": "^1.2.2",
        "wait-on": "^3.3.0"
      }
    },
```

Notice `^3.3.0` and not `^4.0.0`?

**Comment by mxschmitt** [comment]
Seems like a new version needs to be released, because currently its still the [old](https://unpkg.com/jest-dev-server@4.4.0/package.json) version.

A fix was already merged, see PR #316.

**Comment by thernstig** [comment]
@gregberge Sorry for pinging you, but any chance you would want to make a release? :)

**Comment by dartess** [comment]
it would be better to get version 5 now https://github.com/smooth-code/jest-puppeteer/issues/358
