### ISSUE TITLE
jest-dev-server: Support an option for a base path 

### ISSUE THREAD

**Issue by thernstig** [smooth-code/jest-puppeteer#342]
## 🚀 Feature Proposal

Add an option for a basePath where server is running, appended to the host:port. E.g.:

```javascript
module.exports = {
  command: 'npm run start --port 3000',
  host: 'customhost.com',
  port: 3000,
  basePath: 'myservice'
}
```

Would equal to this URL where the server is hosting files: `customhost:3000/myservice`.

## Motivation

Many cloud native apps support setting a basePath, since ingress/proxies/edge routes often host services/apps under a "prefix". Supporting a basePath means that in local development you can test so that your application works properly when using a basePath, verifying it works properly with such ingress/edge proxies.

## Example

See above. Also see e.g. this proxy (most proxies has the same functionality):
https://docs.traefik.io/v1.4/basics/#path-matcher-usage-guidelines

## Pitch

`jest-dev-server` is  used to launch "your own app" to test it e.g. when running locally, and we want to be able to mimic real-life scenarios.

**Comment by kellyjosephprice** [comment]
My workaround:

```
module.exports = {
  command: 'npm run start --port 3000',
  waitOnScheme: {
    resources: [ 'http-get://customhost.com:3000/myservice' ],
  }
}
```

The underlying `wait-on` accepts a url, and it's undocumented, but you can overwrite the options passed to `wait-on`.
