### ISSUE TITLE
How to debug the test code (Node)

### ISSUE THREAD

**Issue by Bnaya** [smooth-code/jest-puppeteer#343]
Given the following example:

```
  it('should display "google" text on page', async () => {
    await jestPuppeteer.debug();
    await expect(page).toMatch('google')
  })
```
I'm running my jest in debug mode, and when the test is on `await jestPuppeteer.debug();`
I want to access the `page` & `browser` from my debug console and run commnds.

When adding a break point, the `page` & `browser` are available on `global.xxx`,
But when a breakpoint is active commands can't run.

So i try to access global.page & global.browser when on `await jestPuppeteer.debug();` & debugger attached, but without breakpoint.
I do have access to `global` on the debug console, but global.page & global.browser are not there.

I've tired to expose them on different names, for no avail:
```
  it('should display "google" text on page', async () => {
    global.anotherName = browser;
    await jestPuppeteer.debug();
    await expect(page).toMatch('google')
  })
```

Thanks!

**Comment by tihuan** [comment]
Not sure if this helps, but have you tried https://github.com/GoogleChromeLabs/ndb?
