### ISSUE TITLE
.on('dialog') prompt does nothing when using slowMo browser option

### ISSUE THREAD

**Issue by ryandougc** [smooth-code/jest-puppeteer#346]
## 🐛 Bug Report

Entering text into a prompt dialog box when using the slowMo option for the browser does not work. The prompt will stay up with no text being entered into it and no action done (accept or decline).

#### JS
```
let name = prompt('What is your name?')
```
#### Test
```
test('reconnect-user', async () => {
    const browser = await puppeteer.launch({
        headless: false
        ,slowMo: 90
        ,args: ['--window-size=1280,720', '--auto-open-devtools-for-tabs']
    })

    const page = await browser.newPage()
    await page.goto('http://localhost:3000/')

    await page.on('dialog', async dialog => {
        await dialog.accept(`puppet`)
    })
})
```

## Expected behavior

I expected the test to input a name into the prompt box and accept the prompt just like it does when the slowMo option is not supplied. 

## Link to repl or repo

https://github.com/ryandougc/multiplayer-tictactoe/tree/puppet-bug

## System:
 - OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
 - CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
 - Memory: 4.56 GB / 15.65 GB
 - Container: Yes
 - Shell: 4.4.20 - /bin/bash
## Binaries:
 - Node: 12.16.2 - /usr/bin/node
 - npm: 6.14.4 - /usr/bin/npm

```bash

```

**Comment by UziTech** [comment]
This seems like an issue for puppeteer not jest-puppeteer
