### ISSUE TITLE
Allow running a test against multiple browsers

### ISSUE THREAD

**Issue by l-abels** [smooth-code/jest-puppeteer#347]
## 🚀 Feature Proposal

Create `test.eachBrowser`, a method that runs a test function for several different browsers.  Allow browsers to be defined in `jest-puppeteer.config.js` as an array of launch options.  These launch option objects would be merged with the launch options defined elsewhere when `test.eachBrowser` is invoked.

`test.eachBrowser` would effectively function like `test.each`, but the inputs are browser configs defined in `jest-puppeteer.config.js`.

## Motivation

Jest 3.0.0 introduces built-in support for Firefox, and Microsoft Edge is already supported as it is Chromium-based.  Testing a website for cross-browser compatibility is very valuable, and `jest-puppeteer` could make it much simpler.

## Example

```
//jest-puppeteer.config.js

module.exports = {
  browsers: {
    chromium: {
      product: 'chromium',
      executablePath: 'path/to/chromium'
    },
    edge: {
      product: 'chromium',
      executablePath: 'path/to/edge'
    },
    firefox: {
      product: 'firefox',
      executablePath: 'path/to/firefox'
    }
  }
}
```

```
//myTests.test.js


//Produces three describe blocks, one for each of the defined browsers.
describe.eachBrowser ('My Web Page', () => {

  it.todo ('Meets a requirement');

})
```

## Pitch

`jest-puppeteer` sits between `puppeteer` and `jest`, making it the perfect place to introduce a `test` extension that controls `puppeteer`.  Currently, the best way to achieve this goal is to run `jest` several times with different env vars.  This new feature would make this process much smoother and produce a single set of test results instead of three.

**Comment by tanvee38** [comment]
Kindly let us know if there is any update on this. it would be a great if we can run same tests across multiple browsers in parallel.

**Comment by ThibaultJanBeyer** [comment]
+1 for this request.

Also, I think the [deprecated puppeteer-firefox](https://github.com/puppeteer/puppeteer/tree/main/experimental/puppeteer-firefox) can be removed in favour of just passing the settings to puppeteer within launch configs as mentioned in the [puppeteer launch options](https://github.com/puppeteer/puppeteer/blob/v5.4.1/docs/api.md#puppeteerlaunchoptions).

I suppose for now you'd have to create separate projects: https://stackoverflow.com/questions/61687259/how-to-use-different-jest-config-js-for-unit-and-component-tests

**Comment by briansanchez** [comment]
+1

**Comment by UziTech** [comment]
Yes you would have to add [`projects`](https://jestjs.io/docs/configuration#projects-arraystring--projectconfig) to your jest configuration.
