### ISSUE TITLE
TypeError: this.global.page.addListener is not a function with puppeteer@3.2.0 

### ISSUE THREAD

**Issue by BryceMehring** [smooth-code/jest-puppeteer#353]
## 🐛 Bug Report

`TypeError: this.global.page.addListener is not a function` is thrown using puppeteer@3.2.0

https://github.com/puppeteer/puppeteer/releases/tag/v3.2.0 

>We now use Mitt as the Event Emitter that backs many of Puppeteer's classes rather than the EventEmitter module that ships with Node. This is potentially a breaking change if you rely on some of the less popular EventEmitter methods as Puppeteer's EventEmitter does not support the entire suite of NodeJS EventEmitter functions. We think it's unlikely anyone has relied on these; we were able to swap out the EventEmitter in Puppeteer without any unit tests needing to change.

**Comment by mthahzan** [comment]
This is [fixed with the release of Puppeteer 3.3.0](https://github.com/puppeteer/puppeteer/issues/5944#issuecomment-637400760)
