### ISSUE TITLE
travis test suites started failing: TypeError: this.global.page.addListener is not a function

### ISSUE THREAD

**Issue by AaronWatters** [smooth-code/jest-puppeteer#354]
## 🐛 Bug Report

All of my jest-puppeteer builds on travis suddenly started failing.
I think some new version of something is breaking because if I check in package-lock.json
the builds started working again.  Here is an example of what I see

from: https://travis-ci.org/github/AaronWatters/jp_proxy_widget/jobs/692688131

```
> jp_proxy_widgets_end_to_end_testing@1.0.0 test /home/travis/build/AaronWatters/jp_proxy_widget/end_to_end_tests
> jest
globalSetup.js started Jupyter
 FAIL  tests/headless.test.js
  ● Test suite failed to run
    TypeError: this.global.page.addListener is not a function
      
      at Object.resetPage (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:105:28)
      at async Object.resetBrowser (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:143:9)
      at async PuppeteerEnvironment.setup (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:146:5)
 FAIL  tests/run_notebooks.test.js
  ● Test suite failed to run
```

After I add package-lock.json to the test suite build the problem disappears (I
assume because I get unbroken older versions of something):

Here is after adding: https://travis-ci.org/github/AaronWatters/jp_proxy_widget/jobs/692699778

## To Reproduce

You could clonehttps://github.com/AaronWatters/hello_jest, remove package-lock.json from the repository and then
set up a travis build.

## Expected behavior

The test suite should start.

## Link to repl or repo (highly encouraged)

I'm seeing this problem in a relatively simple test repository now:

Failing travis build: https://travis-ci.org/github/AaronWatters/hello_jest/builds/692703999

Repository: https://github.com/AaronWatters/hello_jest

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 10.15.5
 - CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
 - Memory: 13.22 GB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.13.0 - ~/anaconda3/bin/node
 - Yarn: 1.12.1 - ~/anaconda3/bin/yarn
 - npm: 6.14.4 - ~/anaconda3/bin/npm
```

**Comment by wheresrhys** [comment]
I'm also seeing similar behaviour in circleci and locally. Trawling through package-lock I think this is the only change https://github.com/zertosh/v8-compile-cache/pull/28, so maybe related to that dependency

**Comment by UziTech** [comment]
is this still an issue?
