### ISSUE TITLE
slowmo causes test to fail

### ISSUE THREAD

**Issue by melissachang** [smooth-code/jest-puppeteer#36]
Repro
- git clone -b jest-puppeteer-36 https://github.com/melissachang/repro-issues.git
- cd repro-issues && npm install
- `npm test` passes
- In `jest-puppeteer.config.js`, uncomment `slowMo` line
- Now `npm test` fails

**Comment by neoziro** [comment]
Actually [expect-puppeteer have a default timeout of 500ms](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer/src/utils.js). This is the cause of the bug. I think I will make it configurable and automatically delay it with `slowMo` option.

**Comment by melissachang** [comment]
I don't care where slowMo default is defined (expect-puppeteer, jest-puppeteer, etc), but can the default be the same as in puppeeter, which I think is 0?

**Comment by neoziro** [comment]
slowMo default is 0, but when you changed it tests have to wait more in order to pass. So this is actually a bug.

**Comment by melissachang** [comment]
Yeah, I guess I'm saying, in addition to fixing the bug, can you also change the expect-puppeteer default to be 0?
