### ISSUE TITLE
beforeunload dialog is not triggered

### ISSUE THREAD

**Issue by khongten001** [smooth-code/jest-puppeteer#362]
As the title, would you please add a option to add {runBeforeUnload: true} when page.close? See: https://stackoverflow.com/questions/50832325/onbeforeunload-not-being-triggered-from-a-headless-browser

Thank you very much

**Comment by Ayc0** [comment]
Related to this, can we make so that `page.close` runs with `page.close({ runBeforeUnload: true })`?

**Comment by UziTech** [comment]
@Ayc0 ya if you could make a PR with that change I could get it merges. Make sure to add tests 😁👍

**Comment by Ayc0** [comment]
@UziTech, I opened https://github.com/smooth-code/jest-puppeteer/pull/504

Does it sound good to you? (It's my first PR on this repo)

**Comment by UziTech** [comment]
Thanks for the PR. I will try to get a new release out in the next week.
