### ISSUE TITLE
[Introduction] Free recorder for creating test suite without coding

### ISSUE THREAD

**Issue by nglthach** [smooth-code/jest-puppeteer#363]
Hi,
I'm  Thach - Smart Monkey's author. 
I have added a functionality to Smart Money for exporting a project to  Puppeteer code. Here is the video for demo:  https://www.youtube.com/watch?v=eBzK85MOo-A

In the most of cases, you don't need to write any line of code for creating a test suite.

Sincerely,
Thach

**Comment by UziTech** [comment]
Is Smart Monkey open source?
