### ISSUE TITLE
How to combine jest-puppeteer and ts-jest?

### ISSUE THREAD

**Issue by tjx666** [smooth-code/jest-puppeteer#364]
I configued it like following, but failed?

![screenshot_2020-07-14_01-07-31](https://user-images.githubusercontent.com/41773861/87332663-7e0bd300-c56e-11ea-81b3-c1790e181336.png)

**Comment by peterekepeter** [comment]
Yep, I had some headaches with this as well, I found somewhere that you can actually combine presets into a new preset. You need something like this:

``` javascript
// preset.js
const ts_preset = require('ts-jest/presets/js-with-babel/jest-preset')
const puppeteer_preset = require('jest-puppeteer/jest-preset')

module.exports = Object.assign(
    ts_preset,
    puppeteer_preset
)
````

then reference it from your config (I prefer to keep it in `package.json`

``` json
{
  "jest": {
    "preset": "./preset",
    "testTimeout": 10000
  }
}
```

**Comment by leosuncin** [comment]
This is my basic setup

**jest-puppeteer.config.js**

```javascript
module.exports = {
  preset: 'jest-puppeteer',
  setupFilesAfterEnv: ['expect-puppeteer'],
  testTimeout: 100000,
  globals: {
    'ts-jest': {
      tsConfig: '<rootDir>/tsconfig.json',
    },
  },
};
```
