### ISSUE TITLE
Something like expect.toURLChange

### ISSUE THREAD

**Issue by peterbe** [smooth-code/jest-puppeteer#365]
## 🚀 Feature Proposal

For the record, I hope this isn't ignorance or a bug report actually.

We have this:
```javascript
await expect(page).toClick('[aria-selected="true"]');
```
which triggers a piece of JS code that uses `window.pushState()` to change the URL and it changes which content to display. All of that JS code is handled by `react-router` if that matters. 

This does NOT work:
```javascript
    await expect(page).toClick('[aria-selected="true"]');
    // Should have been redirected too...
    expect(page.url()).toBe(testURL("/en-US/docs/Web/Foo"));
    await expect(page).toMatchElement("h1", { text: "<foo>: A test tag" });
```

But this DOES work:
```javascript
    await expect(page).toClick('[aria-selected="true"]');
    await expect(page).toMatchElement("h1", { text: "<foo>: A test tag" });
    // Should have been redirected too...
    expect(page.url()).toBe(testURL("/en-US/docs/Web/Foo"));
```

I.e. if you wait for `await expect(page).toMatchElement(` it's waiting long enough that `page.url()` updates. 

I wish there was something like:
```javascript
    await expect(page).toClick('[aria-selected="true"]');
    // Should have been redirected too...
    await expect(page).toURLChange(testURL("/en-US/docs/Web/Foo"));
    await expect(page).toMatchElement("h1", { text: "<foo>: A test tag" });
```

## Motivation

The motivation is that it's explicit that you're waiting for the URL to have changed. It's implicit that you can hack around it by doing the non-await check "later".

## Example

Hopefully the example above is good enough.

## Pitch

I always imagine jest-puppeteer to be the robot I can code to make a QA human jobless. If a human was asked to run the web app on every build I'd have asked him/her to...: "Click on the search result and expect to have gone to this other URL and that the page's header should have changed to $this_title". 

Perhaps the URL change is an implementation detail and not functional enough.

**Comment by peterbe** [comment]
I tried putting in a `await page.waitForNavigation();` right before the `expect(page.url()).toBe(testURL("/en-US/docs/Web/Foo"));` but I don't know for sure if it's rock solid and it's not an `expect-puppeteer` API.

**Comment by peterekepeter** [comment]
this might help: you can split call `page.waitForNavigation();` and await later

``` javascript
const navigation = page.waitForNavigation({ waitUntil: 'networkidle0' });
await expect(page).toClick("a.next-page");
await navigation;
```

As for the proposal itself I think it would be more useful to assert the location not the change, then it does not depend so much on the timing of things and leads to more stable tests

eg:
``` javascript
await expect(page).toClick("a.next-page");
await expect(page).toMatchLocation("/list?page=2");
```

And in case navigation is sloooow:

``` javascript
await expect(page).toClick("a.next-page");
await expect(page).toMatchLocation("/list?page=2", { timeout: 5000 });
```
