### ISSUE TITLE
toFill does not handle checkboxes

### ISSUE THREAD

**Issue by peterekepeter** [smooth-code/jest-puppeteer#373]
## toFill does not handle checkboxes

Trying to fill out checkbox inputs does not work
my current workaround is to execute a javascript on the page.

Having
``` html
<input type="checkbox"/>
```

I would expect

``` javascript
await expect(page).toFill('input', true);
```

to set the checkbox to checked state

**Comment by UziTech** [comment]
`toFill` is for filling a text field with text.
