### ISSUE TITLE
Localhost ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by lithafnium** [smooth-code/jest-puppeteer#385]
## 🐛 Bug Report

Running puppeteer on localhost does not work, returns ERR_CONNECTION_REFUSED when trying to connect using `page.goto("http://localhost:3000")`. I've tried adding timeouts, configuring jest-pupeteer.config.js, rearranging files, etc., but nothing seems to be working. As an aside, calling `npm start` before `npm test` on another terminal window runs the tests successfully, but I would rather not have that so as to reduce confusion when people run tests locally and on Github actions. 

## Link to repl or repo (highly encouraged)

I don't have a repo as this is with a company's codebase but I have my test files and configuration here: 

```
import puppeteer from "puppeteer"
import 'expect-puppeteer'

let browser: puppeteer.Browser 
let page

describe("about page", () => {

  beforeAll(async () => {
    browser= await puppeteer.launch({
      headless: false
    })
    jest.setTimeout(60000)

    page = await browser.newPage()
    await page.goto("http://localhost:3000")
  })
  test("renders about page correctly", async() => {
    
  
  })
})

afterAll(() => {
  browser.close()
})
```

My jest-puppeteer.config.js: 

```
module.exports = {
  launch: {
    headless: process.env.HEADLESS !== 'false',
    timeout: 30000
  },
  server: {
    command: 'PORT=3000 react-scripts start',
    port: 3000,
  },
}

```

jest.config.js: 

```
module.exports = {
  clearMocks: true,
  coverageDirectory: "coverage",
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
  "preset": "jest-puppeteer",
  roots: ["<rootDir>"],
  "testEnvironment": "jest-environment-jsdom-sixteen",
  testRegex: ["(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$"],
  transform: {
        "^.+\\.tsx?$": "ts-jest",
    },
}
```

Script to run tests: 
`        "test": "react-scripts test --env=jest-environment-jsdom-sixteen",
`

```


## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash

```

**Comment by UziTech** [comment]
it looks like your `testEnvironment` is `jest-environment-jsdom-sixteen` not `jest-environment-puppeteer`.

If you remove the `testEnvironment` property from your config and remove `--env=jest-environment-jsdom-sixteen` from the test command, does it work?
