### ISSUE TITLE
Wrong puppeteer version in peerDependency

### ISSUE THREAD

**Issue by MajorMeerkatThe3rd** [smooth-code/jest-puppeteer#393]
## 🐛 Bug Report

The package.json of `jest-puppeteer` in the node_modules in a newly installed `jest-puppeteer` shows `"puppeteer": ">= 1.5.0 < 3"` in the peerDependencies.

## To Reproduce

1. `npm init --yes`
2. `npm i --save-dev jest-puppeteer`

## Expected behavior

Would expected to be `"puppeteer": ">= 1.5.0 < 9"`

## Link to repl or repo (highly encouraged)

See above, should be easy enough to reproduce :)

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: Windows 10 10.0.19042
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 21.92 GB / 31.75 GB
## Binaries:
 - Node: 15.14.0 - C:\Program Files\nodejs\node.EXE
 - npm: 7.7.6 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - jest-puppeteer: ^4.4.0 => 4.4.0
```

**Comment by UziTech** [comment]
This is fixed in master and will be released soon.
