### ISSUE TITLE
Unable to resolve dependency tree with puppeteer v3+

### ISSUE THREAD

**Issue by dalelotts** [smooth-code/jest-puppeteer#394]
## 🐛 Bug Report
 ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: app@1.0.0
npm ERR! Found: puppeteer@8.0.0
npm ERR! node_modules/puppeteer
npm ERR!   dev puppeteer@"^8.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer puppeteer@">= 1.5.0 < 3" from jest-puppeteer@4.4.0
npm ERR! node_modules/jest-puppeteer
npm ERR!   dev jest-puppeteer@"^4.4.0" from the root project

## To Reproduce

1. User installs puppeteer and jest, but not jest-puppeteer
   `npm install --save-dev puppeteer jest`
2. then later installs jest-puppeteer
    `npm install --save-dev jest-puppeteer`

## Expected behavior

jest-puppeteer works with puppeteer version 3 and higher. Current version is 8.0.0

## Link to repl or repo (highly encouraged)

```shell
mkdir jest-puppeteer-peer-problem
cd  jest-puppeteer-peer-problem
npm init -y
npm install --save-dev puppeteer jest
npm install --save-dev jest-puppeteer
```

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
*** Clipboard option removed - use clipboardy or clipboard-cli directly ***

## System:
 - OS: macOS 11.2.3
 - CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
 - Memory: 71.52 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
 - npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
 ```

**Comment by UziTech** [comment]
This is fixed in master and will be released soon

**Comment by dalelotts** [comment]
Maybe have a look at [semantic-release]( https://github.com/semantic-release/semantic-release ) so the release of fixes is not delayed.

**Comment by UziTech** [comment]
@dalelotts if you know how to get semantic release to work with lerna a PR would be very much appreciated. 😁👍

**Comment by dalelotts** [comment]
I can do that.  Anything to get on the contributors list. 😀

Can you tell me a bit about how you manually release?  Do you release all packages at the same time with the same versions?  Is each versioned independently?

**Comment by UziTech** [comment]
each has the same version. We use [lerna](https://github.com/lerna/lerna) to publish all packages with `yarn release`
