### ISSUE TITLE
Server keeps running

### ISSUE THREAD

**Issue by steve-taylor** [smooth-code/jest-puppeteer#407]
## 🐛 Bug Report

When running `yarn test:integrationWithWatch` in the create-react-app example a second time, it doesn't run any tests, then exits.

## To Reproduce

1. Clone this repo
2. `cd examples/create-react-app && yarn && yarn test:integrationWithWatch`
3. Press "a" to run all tests.
4. After all tests have run, press "q" to quit.
5. `yarn test:integrationWithWatch`

## Expected behavior

1. All tests are executed.
2. After executing tests, Jest watches for changes instead of terminating.

## Link to repl or repo (highly encouraged)

See the example in this repo.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 11.2.3
 - CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 417.59 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v16.1.0/bin/yarn
 - npm: 7.11.2 - ~/.nvm/versions/node/v16.1.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - jest-puppeteer: ^4.4.0 => 4.4.0
```

**Comment by UziTech** [comment]
Can you update jest-puppeteer to the latest version and see if it still happens?
