### ISSUE TITLE
One browser instance per test suite

### ISSUE THREAD

**Issue by delijah** [smooth-code/jest-puppeteer#409]
## 💬 Questions and Help

Hey!

We are doing visual regression testing using puppeteer in our stack. Currently we are using a custom built solution using puppeteer, but are considering to switch to jest-puppeteer. At the moment we face performance issues on our way there. I'll try to explain:

jest-environment-puppeteer launches one chromium instance for all tests and creates a page per test suite. If we run this with multiple workers (one per cpu, which means we would have running 1 chrome instance with 6 open tabs if we run it on a machine with 6 cpus) we get a lot of timeouts we did not get before. And it's random (on every run, another test suite times out).

In our current custom solution we run a chromium instance per test suite (which means we have 6 chromium instances running with each 1 tab, on a machine with 6 cpus). Here we experience almost no timeouts. So somehow this seems to run much more performant.

So a question which arises in my mind is: could we add a config option to jest-environment-puppeteer, to either run it
- With 1 chromium instance over all and 1 tab/page per test suite
- With 1 chromium instance per test suite (with each only 1 tab/page open)

Or maybe you do have other ideas?

Thanks for your perspectives in advance!

**Comment by UziTech** [comment]
> With 1 chromium instance over all and 1 tab/page per test suite

I don't know if this is possible. I may be wrong but I think since jest is multi-threaded it requires different environments for each test suite.

> With 1 chromium instance per test suite (with each only 1 tab/page open)

I'm pretty sure this is already how it works. unless you call `jestPuppeteer.resetPage()` or `jestPuppeteer.resetBrowser()` all tests in one suite will be run in the same page.

You can look at [example 2](https://github.com/smooth-code/jest-puppeteer/tree/master/packages/jest-environment-puppeteer#example-2) in the readme on how to connect to an already running instance of chrome.

**Comment by delijah** [comment]
> I'm pretty sure this is already how it works. unless you call `jestPuppeteer.resetPage()` or `jestPuppeteer.resetBrowser()` all tests in one suite will be run in the same page.

Hmmm, actually no, not really. I've tested this again right now to be really sure. How it works at the moment with using jest and jest-puppeteer is: Jest is using one chromium instance over all test suites and opens up one tab/page per test suite in order to run the tests in.

**Comment by delijah** [comment]
> You can look at [example 2](https://github.com/smooth-code/jest-puppeteer/tree/master/packages/jest-environment-puppeteer#example-2) in the readme on how to connect to an already running instance of chrome.

What i am looking for is a way to use a separate chromium instance per test suite/worker.

Thanks anyways so far for your replies :)

**Comment by UziTech** [comment]
It looks like we would have to find a way to run `setup` and `teardown` from https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-environment-puppeteer/src/global.js for each test suite. If you would like to create a PR for a setting that does this I would be ok with it.
