### ISSUE TITLE
Fresh install doesn't work

### ISSUE THREAD

**Issue by melissachang** [smooth-code/jest-puppeteer#42]
- Install jest globally with 'npm install -g jest'
- Create a directory and `cd` into it
- Put into `package.json`:
```
{
  "jest": {
    "preset": "jest-puppeteer"
  }
}
```
- `npm install --save-dev jest-puppeteer puppeteer`
Note this warning is printed:
```
npm WARN jest-environment-puppeteer@2.3.0 requires a peer of jest-environment-node@^22.0.0 but none is installed. You must install peer dependencies yourself.
```
Also note that `node_modules/jest-environment-node` doesn't exit.
- Put [sample code](https://github.com/smooth-code/jest-puppeteer#usage) into test.js
- `jest test.js` gives this error:
```
~/repro-issues (jest): jest test.js 
 FAIL  ./test.js
  ● Test suite failed to run

    Cannot find module 'jest-environment-node'
      
      at Object.<anonymous> (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:9:28)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.05s, estimated 3s
Ran all test suites matching /test.js/i.
```
- `npm install --save-dev jest-environment-node@22.0.0`. Now `jest test.js` works.

This happens because of this [peer dependency](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-environment-puppeteer/package.json#L24). With npm, [peer dependencies must be manually installed](https://nodejs.org/en/blog/npm/peer-dependencies/#using-peer-dependencies). This [SO answer](https://stackoverflow.com/questions/26737819/why-use-peer-dependencies-in-npm-for-plugins) explains when to use peer dependencies.

@neoziro, can these be regular dependencies instead of peer?

**Comment by neoziro** [comment]
I thought that `jest-environment-node` was installed with `jest` that's why it is a peer dependency. I will check but if it is not the case it makes sense to add move it into `dependencies`.

**Comment by neoziro** [comment]
I have just tested to install jest locally and it installs `jest-environment-node/`. Installing `jest` globally is not a good practice, so please install it locally and everything will work.

**Comment by melissachang** [comment]
Even with jest global, fresh install doesn't work. You either need to add `jest-environment-node` to the [`npm install` command](https://github.com/smooth-code/jest-puppeteer#jest-puppeteer), or take out peer dependencies. Why not take out peer dependencies, they just complicate things?

Repro steps without global jest:
- Create a directory and `cd` into it
- Put into `package.json`:
```
{
  "scripts": {
    "test": "jest"
  },
  "jest": {
    "preset": "jest-puppeteer"
  }
}
```
- `npm install --save-dev jest-puppeteer puppeteer`
Note this warning is printed:
```
npm WARN jest-environment-puppeteer@2.4.0 requires a peer of jest-environment-node@^22.0.0 but none is installed. You must install peer dependencies yourself.
```
Also note that `node_modules/jest-environment-node` doesn't exit.
- Put [sample code](https://github.com/smooth-code/jest-puppeteer#usage) into test.js
- `jest test.js` gives this error:
```
npm test
 FAIL  ./test.js
  ● Test suite failed to run

    Cannot find module 'jest-environment-node'
      
      at Object.<anonymous> (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:9:28)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.05s, estimated 3s
Ran all test suites matching /test.js/i.
```
- `npm install --save-dev jest-environment-node@22.0.0`. Now `npm test` works.
