### ISSUE TITLE
Server folder usage

### ISSUE THREAD

**Issue by AmitKulkarni9** [smooth-code/jest-puppeteer#431]
Why server folder is required to run jest-puppeteer tests. If I exclude it I get below error:

> jest --verbose --no-cache --runInBand

Determining test suites to run...internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\...\server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Regards,
Amit

## 💬 Questions and Help

Jest Puppeteer project is young, but please before asking your question:

- Read carefully the README of the project
- Search if your answer has already been answered in old issues

After you can submit your question and we will be happy to help you!

**Comment by UziTech** [comment]
server isn't required unless you specify it in your config file. Can you share your config and setup?

**Comment by AmitKulkarni9** [comment]
Thanks UziTech. 
That was great hint. I removed the server details from jest-puppeteer.config.js and removed server folder and it is working.
