### ISSUE TITLE
Test launches additional browser before test starts

### ISSUE THREAD

**Issue by AmitKulkarni9** [smooth-code/jest-puppeteer#432]
I am having all the default configs as is for jest.config, jest-puppeteer.config,babel.config,eslintrc.js. I am running simple test to launch the browser in headless mode but I see browser opens as soon as I start test by "npm test"  ? why and from where does the browser gets launched ?

Test:
const puppeteer = require('puppeteer');
import 'expect-puppeteer'

let browser;  
let page;

describe('Google', () => {
  beforeAll(async () => {
    browser = await puppeteer.launch();
    page = await browser.newPage();
    await page.goto('https://google.com')
  })

  it('should display "google" text on page', async () => {
    await expect(page).toMatch('google')
    await page.close();
    await browser.close();
  })
})

**Comment by UziTech** [comment]
see the example app in https://github.com/smooth-code/jest-puppeteer/tree/master/examples/create-react-app.

You don't need to launch puppeteer yourself in the tests the jest-puppeteer-environment will do that.

**Comment by AmitKulkarni9** [comment]
OK, so jest-puppeteer-environment launches the default browser. And that is the recommended option? I have modified my test to not launch browser and in headless mode. But it will still launch the non-headless browser (from jest-puppeteer-environment).

Can we make jest-puppeteer-environment browser headless ? and How ?

**Comment by UziTech** [comment]
[`headless` option](https://github.com/smooth-code/jest-puppeteer#configure-puppeteer)

**Comment by AmitKulkarni9** [comment]
Thanks UziTech, 
headless: process.env.HEADLESS !== 'false', makes it headless.

Can we configure to make it work from commandline ?

**Comment by AmitKulkarni9** [comment]
Hi UziTech,
figured out to run in commandline both headless and non-headless

 "test": "cross-env HEADLESS=true jest --verbose --no-cache --runInBand",
 "test:nonheadless": "cross-env HEADLESS=false jest --verbose --no-cache --runInBand"

**Comment by UziTech** [comment]
You can also configure it in `jest-puppeteer.config.js`

```js
// jest-puppeteer.config.js
module.exports = {
  launch: {
    headless: true
  }
}
```
