### ISSUE TITLE
Pseudoclass tests doesn't work in docker

### ISSUE THREAD

**Issue by nosooqua** [smooth-code/jest-puppeteer#433]
Hello, I'm trying to test a component using a :visited pseudo-class. When I debug this test not in Docker, everything is fine. But if I start this test in docker , I will get a screenshot without the visited state.

What I get in browser:
<img width="526" alt="Screen Shot 2021-08-20 at 12 14 04" src="https://user-images.githubusercontent.com/35642108/130214501-cd53dbf8-4df0-4538-abf7-b9c94dd218c6.png">

What I get in Docker, test screenshot:
<img width="787" alt="Screen Shot 2021-08-20 at 12 15 48" src="https://user-images.githubusercontent.com/35642108/130214610-73cf3d4b-07af-47e4-90a8-16707fe9bd86.png">

Code:
![image](https://user-images.githubusercontent.com/35642108/130214748-03904a7f-c19a-4ed7-8149-4baff0183110.png)

**Comment by UziTech** [comment]
I am unable to reproduce this. Can you create a repo with a minimal example so I can check it out?

**Comment by UziTech** [comment]
closing as stale
