### ISSUE TITLE
Update Peer Dependency of Puppeteer to >=1.5.0

### ISSUE THREAD

**Issue by rodoabad** [smooth-code/jest-puppeteer#438]
```
npm ERR! Could not resolve dependency:
npm ERR! peer puppeteer@">= 1.5.0 < 10" from jest-puppeteer@5.0.4
```

Limiting to less earlier versions of Puppeteer severely limits the usage of this package for NPM 7 users as we have to install with `--legacy-peer-deps`.

**Comment by UziTech** [comment]
what is your proposed solution?

**Comment by MartinFalatic** [comment]
@UziTech Can the upper bound of `< 10` be removed or increased to allow more recent puppeteer versions?
