### ISSUE TITLE
Enabling spawned server output (stdout, stderr) for debugging

### ISSUE THREAD

**Issue by mhipszki** [smooth-code/jest-puppeteer#44]
When a server command is specified in `jest-puppeteer.config.js` but for some reason e.g. misconfigured port etc. we cannot connect to the spawned server, Jest will just hang forever in a state `Determining test suites to run...`

<img width="305" alt="screen shot 2018-04-19 at 8 57 09 am" src="https://user-images.githubusercontent.com/220661/38979142-4827dafe-43b1-11e8-831f-3a1d3bfb95f5.png">

Actually when the ports are not matching this it waits forever for the port to be opened:

```js
    if (config.server.port) {
      await waitPort({ port: config.server.port, output: 'silent' })
    }
```

Adding e.g. a `debug` option to the server config could help developers to find out what's causing the issue e.g.

```js
// jest-puppeteer.config.js
module.exports = {
  server: {
    command: 'node server.js',
    port: 4444,
    debug: true
  },
}
```

The implementation is simple, the spawned child process needs listeners on both `stdout` and `stderr` so that we can console.log whatever happens in there:

```js
    server = spawnd(config.server.command, {
      shell: true,
      env: process.env,
      cwd: cwd(),
      ...config.server.options,
    })

    // allow logging the spawned process output to our own shell
    if (config.server.debug) {
      server.stdout.on('data', data => {
        console.log(data)
      })

      server.stderr.on('data', data => {
        console.log(data)
      })
    }
```

Also the `output: 'silent'`  option of `wait-port` could be turned off to show that we're actually waiting for the port to be opened.

```js
    if (config.server.port) {
      await waitPort({ port: config.server.port, ...!debug && { output: 'silent' } })
    }
```

**Comment by mhipszki** [comment]
I'm happy to create a PR for this if there's interest.

**Comment by neoziro** [comment]
Yes I would be happy to have that feature, also I think we should be able to define a timeout to avoid waiting forever. Can you do this? Thanks!
