### ISSUE TITLE
How to get clean page in one test, while sharing browsing data in others? 

### ISSUE THREAD

**Issue by 4ekki** [smooth-code/jest-puppeteer#449]
When I write tests, I use `page` object to interact with currently opened tab. How is it possible to clear all the data, like cookies, history and localStorage items from this page? 

Imagine I have some personal cabinet app for test and 3 test files: 
```
- tests
---internal-test-1.test.ts
---internal-test-2.test.ts
---login.test.ts
```
I run tests in band (--runInBand jest flag), one-by-one, but the order is random. I use `default` browserContext, so all tests share data. My app uses some property in localStorage for keeping the session, so if I successfully login during `internal-test-1`, I don't have to do so during `internal-test-2`. However, in `login` I need a clean page, without any stored data. 
So in top-level beforeAll block of `login` I want to: 
- either recreate `page` from incognito context
- or clear everything from current `page` object. 

I've tried cleaning data via CDP, but it doesn't affect local storage: 
```
 const client = await page.target().createCDPSession();
    await client.send("Network.clearBrowserCookies");
    await client.send("Network.clearBrowserCache");
```
I've tried resetting browser and page, but no visible result either (btw, it's unclear from [documentation](https://github.com/smooth-code/jest-puppeteer#globaljestpuppeteerresetpage) exactly these methods should do): 
```
await jestPuppeteer.resetPage()
await jestPuppeteer.resetBrowser()
```

Can you please advise?

**Comment by UziTech** [comment]
`resetPage` is like close and open page
`resetBrowser` creates a new browser context

`resetBrowser` should do what you want.

**Comment by 4ekki** [comment]
@UziTech, sole `resetBrowser` doesn't help. However, managed to handle my case by doing all actions one-by-one: 
- jestPuppeteer.resetBrowser()
- clear cookies via CDP
- clear localStorage via page.evaluate()

Probably, a bit overhead, but it gets things done =)
