### ISSUE TITLE
"Failed to launch the browser process!" in Github actions

### ISSUE THREAD

**Issue by rap2hpoutre** [smooth-code/jest-puppeteer#451]
Hi 👋  I have this error without specific configuration in github actions:

```
yarn --cwd ./tests test
  shell: sh -e {0}
yarn run v1.22.15
$ jest --runInBand
Error: Jest: Got error running globalSetup - /__w/mano/mano/tests/node_modules/jest-environment-puppeteer/setup.js, reason: Failed to launch the browser process!
/__w/mano/mano/tests/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

Source: https://github.com/SocialGouv/mano/runs/4253539620?check_suite_focus=true

I don't know what to do to fix it, since I did not do anything particular I guess. Thank you 🙏

**Comment by UziTech** [comment]
Looks like it might have been a change in GitHub actions or an update to chrome that caused that error. I would try reaching out GitHub to see if they have a fix.
