### ISSUE TITLE
Puppeteer 13.0.0

### ISSUE THREAD

**Issue by rasco** [smooth-code/jest-puppeteer#461]
## 🐛 Bug Report

I'm not sure if this is a Puppeteer error or an issue with jest-puppeteer, or just an incompatibility introduced in 13.0.0.

The matchers expect.toMatch and expect.toMatchElement don't seem to work anymore with this version of Puppeteer.

## To Reproduce

This line:
`await expect(page).toMatch('Hello world')`
is working perfectly with Puppeteer 9.1.1. 
But with 13.0.0 I get an error like this:

```
    Text not found "Hello world"
    Evaluation failed: TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))

      at eval (eval at waitForPredicatePageFunction (:3:23), <anonymous>:7:36)
      at eval (eval at waitForPredicatePageFunction (:3:23), <anonymous>:16:7)
      at onRaf (__puppeteer_evaluation_script__:50:35)
      at pollRaf (__puppeteer_evaluation_script__:43:15)
      at waitForPredicatePageFunction (__puppeteer_evaluation_script__:8:22)
```

I tried it with
```
"dependencies": {
    "got": "^12.0.0",
    "jest": "^27.4.4",
    "jest-puppeteer": "^6.0.2",
    "puppeteer": "13.0.0"
  },
```
and
"jest": {
    "preset": "jest-puppeteer",
}
in package.json 
And I tried it with headless set to true and false.
Screenshotting the page showed that it was running correctly otherwise.

## Expected behavior

Should match and not throw an error.

**Comment by simonhammes** [comment]
This issue might be related to https://github.com/puppeteer/puppeteer/issues/7836.
Maybe try running the tests with puppeteer 12 to see if the upgrade to 13 is the one causing problems.

**Comment by jamesgpearce** [comment]
Can repro with Puppeteer 13.0.0 (and can also confirm it works fine against 12.0.1).

**Comment by jamesgpearce** [comment]
Puppeteer 13.0.1 was released to fix this; double check but you might be able to close this issue now.
