### ISSUE TITLE
'page' is not defined. eslint(no-undef)

### ISSUE THREAD

**Issue by z0ccc** [smooth-code/jest-puppeteer#490]
## 💬 Questions and Help

Hi,
I'm wondering if anyone knows why I'm seeing `'page' is not defined` errors in my test file. 

I followed the steps here: https://jestjs.io/docs/configuration

- I have installed jest-puppeteer with yarn,
- I created a jest.config,js:
```
module.exports = {
  preset: 'jest-puppeteer',
}
```
- I then created a test using the example code in test/index.test.js

The test is successful when I run `yarn test` but  I'm still getting errors in index.test.js saying  `'page' is not defined. eslint(no-undef)`

Thanks

**Comment by UziTech** [comment]
What version of jest and puppeteer?
