### ISSUE TITLE
[expect-puppeteer] TypeErrors when using with Puppeteer greather than 18.0.4 version

### ISSUE THREAD

**Issue by KaMa75** [smooth-code/jest-puppeteer#496]
Starting of [Puppeteer v 18.0.4](https://github.com/puppeteer/puppeteer/pull/8994) I'm getting an errors

> TypeError: expect(...).toClick is not a function

> TypeError: expect(...).toFill is not a function

e.t.c, in any test using expect-puppeteer. Is it a known issue?

**Comment by gfoidl** [comment]
It's the same as https://github.com/smooth-code/jest-puppeteer/issues/494?

**Comment by UziTech** [comment]
Closing as duplicate  of #494
