### ISSUE TITLE
expect-puppeteer: change `toMatch` `text` matcher to check if argument is regex or not to match

### ISSUE THREAD

**Issue by rkoval** [smooth-code/jest-puppeteer#50]
First and foremost, I just want to express gratitude for maintaining this project! It's a crucial resource for doing anything with jest and puppeteer.

One pain point though is from usage of `text` matching option on some of the matchers (e.g., `toMatch` or `toMatchElement`). It's confusing (especially for newcomers) that the string you pass to it is actually used as a regex. I realized that it's documented this way, but it would be a lot nicer if the library could do a `typeof` to check if the argument is a `string` or `object` (regex's actual type from what I can tell). Then, it just does a simple `includes` or an actual `match` on the `textContent` respectively. I've run into weird cases where I'm trying to match on money values (e.g., `'$1000'`) and i've found myself beating my head on more than one occasion trying to figure out why text won't match (the `$` is not escaped, obviously). Also, sometimes all you really need is a simple `string` match without needing to remember to escape everything in the regex for what you're matching.

I know that this would bring about a breaking change, so it might not be something you'd be thrilled to add right now. However, I think it could definitely help for readability and usability of this library.

**Comment by rkoval** [comment]
Additionally (although potentially a different issue), when matching on `textContent`, a lot of the time, there will be extra whitespace/newlines surrounding the text you're matching based on how big the DOM tree is within the element you're matching. It could be nice to strip all of the redundant whitespace out when doing the comparison within this library as well such that consumers of it don't need to account for that whitespace in their comparison strings.

For example, a `textContent` of 
```
'    white  

  space   '
``` 
could be stripped to just 
```
'white space'
```
 to allow matching by passing just `'white space'` without needing wildcards in the comparison string.

**Comment by neoziro** [comment]
I think it is a good move. Since it is not possible to pass object to [`waitForFunction`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitforfunctionpagefunction-options-args), the best way to implement it is to use [RegExp source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/source) and add another argument to say if it is a RegExp or not.

Yeah it is a breaking change but I am OK for it. PR welcome.
