### ISSUE TITLE
This link "All Puppeteer launch options" in README.md opens is 404 

### ISSUE THREAD

**Issue by uovol** [smooth-code/jest-puppeteer#500]
![image](https://user-images.githubusercontent.com/22807971/199908598-0eb369c9-6252-4d47-b5ba-418cb5dec312.png)

Click to open the link is "https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteerlaunchoptions" display 404

It may have been replaced by this link: "https://github.com/puppeteer/puppeteer/blob/main/docs/api/puppeteer.puppeteerlaunchoptions.md"

But I'm not sure if it is

**Comment by UziTech** [comment]
Nice catch! That looks right. If you want to create a PR to update it that would be very much appreciated 😁👍
