### ISSUE TITLE
Spinning server environment spawning into a separate module?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [smooth-code/jest-puppeteer#62]
The `jest-puppeteer` preset has been working great for tests with Jest & Puppeteer. However, I'd like to switch to cross-browser Selenium tests. The launching of a server in setup and killing it in teardown is great and it looks like the logic to spawn a server if `config.server` exists is separate from spinning up a Puppeteer page. Do you think it could be moved into a separate module separate from Puppeteer?

In `lib/global.js`, it could `import { setup, teardown } from "jest-server"`. `setup` could `await teardown();` after creating the browser and `teardown` could `await teardown();` before closing the browser.

**Comment by neoziro** [comment]
In fact I already did it, I created a separated module called [spawnd](https://github.com/smooth-code/jest-puppeteer/tree/master/packages/spawnd) to spawn an interdependent process. The code to run the server is in [`global.js`](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-environment-puppeteer/src/global.js), you can just use `spawnd` and spawn your own server. I use [`wait-port`](https://github.com/dwmkerr/wait-port) to wait for the server port to be ready. You have all you need to do it yourself!

Of course if you do it by your own, remove the `config.server`.

**Comment by JoshuaKGoldberg** [comment]
Awesome.

I couldn't directly import from `global.js` because it also manages the global browser, so I copy & pasted code into https://github.com/JoshuaKGoldberg/jest-dev-server. It's pretty blatantly a copy and paste 😄; if you want to take the [`jest-dev-server` npm package](http://npmjs.com/package/jest-dev-server) package let me know and I'll hand it over!

**Comment by neoziro** [comment]
Ah OK I didn't understood your use-case sorry. Yeah why not putting this piece of code in this repository, it will be easier to maintain. I you want to create a PR you are welcome (contributor), else I can do it. About the npm name, can you add me as a owner? Thanks!

**Comment by JoshuaKGoldberg** [comment]
@neoziro added `neoziro` via `npm owner add`. Please let me know if there's any more you'd like me to do!

**Comment by neoziro** [comment]
I am working on it, all good on your side. I have still some work, will try to do it today.
