### ISSUE TITLE
Timeout - Async callback was not invoked

### ISSUE THREAD

**Issue by qcgm1978** [smooth-code/jest-puppeteer#7]
I try executing the demo code in README and it prompts me ' within the 10000ms timeout specified by jest.setTimeout.'
```describe('Google', () => {
  beforeAll(async () => {
    await page.goto('https://www.google.com.hk')
  })

  it('should display "google" text on page', async () => {
    await expect(page).toMatch('google')
  })
})```

**Comment by neoziro** [comment]
I don't understand, you mean it is not working?

**Comment by neoziro** [comment]
@qcgm1978 any update?

**Comment by Niceplace** [comment]
@qcgm1978 If the test's running time > what is passed to jest.setTimeout, apparently jest kills the test.
Puppeteer's default timeouts being 30 seconds, you will never reach the actual timeout of puppeteer before jest kills it. 

You need to make sure that your jest timeout is always superior to the sum of all the timeouts possible inside the test. You could call setTimeout(60000) and specify a timeout in `toMatch` as such `await expect(page).toMatch('google', { timeout: 30000 })`.

This project sets the default timeout for `toMatch` at 500 ms, as specified here (https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer/README.md#toMatch)

**Comment by rodoabad** [comment]
@Niceplace are you able to run the test on this repository without timing out? https://github.com/rodoabad/furry-goggles
