### ISSUE TITLE
Option to check & allow existing port usage in jest-dev-server?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [smooth-code/jest-puppeteer#71]
I'm using this with a create-react-app fork and starting the server takes up a bunch of seconds. It'd be useful to allow developers and CI machines to have a local server running that was started before tests run. That way, if we want to run several runs of tests, we don't have to start the server up each time: the tests can run immediately. We also wouldn't have to manually close our servers before running tests

Can the dev server config logic have a flag to check for the existing port being used, and not start the server if so?

I'd be very open to adding this in. :)

**Comment by anton164** [comment]
Still getting `EADDRINUSE` with `userdPortAction: "ignore"`?

```
$ ./node_modules/.bin/jest
Determining test suites to run...[0622/101431.683618:ERROR:gpu_process_transport_factory.cc(1039)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:58544/devtools/browser/e60a6086-5262-48a9-872b-98cd5a037db7
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8083
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1366:14)
    at listenInCluster (net.js:1407:12)
    at doListen (net.js:1522:7)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
error Command failed with exit code 1.
```

**Comment by nwingert** [comment]
Same experience as @anton164 with 'ignore' option here

**Comment by neoziro** [comment]
`usedPortAction` must be define in `server` section.

**Comment by nwingert** [comment]
![jp_server_port](https://user-images.githubusercontent.com/30574536/41807446-62c2b33a-768c-11e8-8fee-70b2c33054e7.png)

Not sure I understand the response/issue-close here...in my case I believe `usedPortAction` was defined in `server` section? Before I defined `usedPortAction` explicitly the default option of `ask` did not  function as described in documentation either.

**Comment by anton164** [comment]
Yupp, I'm experiencing the exact same issue as Nathan.

**Comment by vitormv** [comment]
@neoziro im also having the same problem here. my `usedPortAction` IS defined in the server section of the configs, but the option is just ignored, same as @nwingert posted.
