### ISSUE TITLE
Cannot read property 'removeListener' of undefined

### ISSUE THREAD

**Issue by t-kelly** [smooth-code/jest-puppeteer#72]
Trying to run jest-puppeteer on `*.puppeteer.test.js` files and JSDom on `*.test.js` files by using [projects](https://facebook.github.io/jest/docs/en/configuration.html#projects-array-string-projectconfig). My `jest.config.js` looks something like:

```js
module.exports = {
  projects: [
    {
      displayName: "jsdom",
      testPathIgnorePatterns: ["puppeteer.test.js$"]
    },
    {
      displayName: "puppeteer",
      preset: "jest-puppeteer",
      setupTestFrameworkScriptFile: "expect-puppeteer",
      testMatch: ["**/*.puppeteer.test.js"]
    }
  ]
};
```
Run I run Jest, I get the following error:
```bash
TypeError: Cannot read property 'removeListener' of undefined

      at PuppeteerEnvironment.teardown (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:50:22)
          at Generator.throw (<anonymous>)
```

Same error occurs if I specify the following docBlock at the top of a `.puppeteer.test.js` file:
```
/**
 * @jest-environment puppeteer
 */
```

Related: https://github.com/facebook/jest/issues/6026, https://github.com/facebook/jest/issues/5441

**Comment by neoziro** [comment]
Jest Puppeteer requires a `globalSetup` and a `globalTeardown` (defined in preset). You can't specify it for a specific project since it is global. So you have to specify the preset at top level of configuration. No bug 😌.

**Comment by DanielDeychakiwsky** [comment]
@t-kelly did you ever resolve this?

**Comment by t-kelly** [comment]
@DanielDeychakiwsky I'm defaulting to jest-puppeteer in my jest.config.yml, and then specifying
```
/**
 * @jest-environment jsdom
 */
```
for test files I want to use JSDom.

**Comment by hegelstad** [comment]
I still get this!

```javascript
TypeError: Cannot read property 'removeListener' of undefined

at ArdoqPuppeteerEnvironment.teardown (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:111:22)
      at ArdoqPuppeteerEnvironment.teardown (test/browser/ardoqPuppeteerEnvironment.js:13:17)
          at Generator.throw (<anonymous>)
```

It is there regardless of if i set exitOnPageError to true or false...

Other relevant info:
jest 23.5.0
puppeteer: 1.7.0
jest-puppeteer: 3.3.0

also using config to run a webpack-dev-server.

**Comment by hegelstad** [comment]
I still get this!

```javascript
TypeError: Cannot read property 'removeListener' of undefined

at CustomPuppeteerEnvironment.teardown (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:111:22)
      at CustomPuppeteerEnvironment.teardown (test/browser/customPuppeteerEnvironment.js:13:17)
          at Generator.throw (<anonymous>)
```

It is there regardless of if i set exitOnPageError to true or false...

Other relevant info:
jest 23.5.0
puppeteer: 1.7.0
jest-puppeteer: 3.3.0

also using config to run a webpack-dev-server.

**Comment by ersinerdal** [comment]
we are also getting the same error

`TypeError: Cannot read property 'removeListener' of undefined

      at PuppeteerEnvironment.teardown (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:109:22)
          at Generator.throw (<anonymous>)
`
remove     "preset": "jest-puppeteer" and run tests, it fails.
then add it back and run, it passes!

 "jest": "^23.5.0",
 "jest-puppeteer": "^3.3.0",
 "puppeteer": "^1.7.0"

**Comment by neoziro** [comment]
Is it a regression since 3.3.0? Can you please open a new issue. This one is closed.
