### ISSUE TITLE
expect-puppeteer: Support XPATH selectors

### ISSUE THREAD

**Issue by testerez** [smooth-code/jest-puppeteer#77]
From what I can see expect-puppeteer does not support XPath selector. XPath could be useful to select elements based on text content for example.
Would you be interested in adding support for XPath?

A possible API could be to accept either a string or a selector object. So for example you could do:

```js
expect(page).toClick('#myId');

// or

expect(page).toClick({value: '#myId', type: 'css'});

// or

expect(page).toClick(
  {value: 'text()[starts-with(., "myText")]]', type: 'xpath'}
);
```

Does it make sense?

**Comment by neoziro** [comment]
I think it is interesting, but we have to think about the API.

**Comment by neoziro** [comment]
Follow up in #132
