### ISSUE TITLE
expect-puppeteer readme out of date?

### ISSUE THREAD

**Issue by callumlocke** [smooth-code/jest-puppeteer#79]
The [toMatch docs](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer/README.md#expectinstancetomatchmatcher-options) for expect-puppeteer has a code example saying `await expect(page).toMatch('lo.*')` will match the string as a RegExp, but the changelog says this is no longer possible, unless I've misunderstood?

**Comment by neoziro** [comment]
Yeah, it is a mistake in the readme.

**Comment by neoziro** [comment]
Fixed in b397f0ea952716f82fe91fe052654a611ee58da7
