### ISSUE TITLE
globalSetup and a globalTeardown aren't optional

### ISSUE THREAD

**Issue by donaldpipowitch** [smooth-code/jest-puppeteer#82]
Hi! I just play around with your lib and it looks like I _need_ to specify a `globalSetup` and `globalTeardown`, even though I just use the default behaviour (see https://github.com/Mercateo/e2e-check/blob/master/packages/puppeteer/global-setup.js).

If I don't specify these files I get this error:

```
TypeError: Cannot read property 'removeListener' of undefined

      at PuppeteerEnvironment.teardown (../../node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:108:22)
          at Generator.throw (<anonymous>)
```

Reading the README it sounds to me, that they should be optional...? Thank you for the lib.

**Comment by neoziro** [comment]
This is because you didn't use the preset: https://github.com/smooth-code/jest-puppeteer#usage

It is not optional but it is filled in the preset.

**Comment by donaldpipowitch** [comment]
Ah, I see. Thanks.
