### ISSUE TITLE
Expect .toClick() to click innermost div that matches textContent

### ISSUE THREAD

**Issue by sethlesky** [smooth-code/jest-puppeteer#84]
Assuming I have the following HTML:
```
    <div>
        <div>
            <div class="box" onclick="console.log('One')">One</div>
            <div class="box" onclick="console.log('Two')">Two</div>
            <div class="box" onclick="console.log('Three')">Three</div>
        </div>
    </div>
```

And I'm attempting to click the div with textContent matching "One":
```
await expect(page).toClick('div', { text: 'One' })
```

I'd expect the div with textContent matching "One" to be clicked, instead, any of the three divs could be clicked.

This seems to be due to the fact .find() returns the first match (always the outermost div) in the following code:
https://github.com/smooth-code/jest-puppeteer/blob/d06f58feca62d5ea5225d53a20035db6dd82d750/packages/expect-puppeteer/src/matchers/toMatchElement.js#L27

To always select the element with the innermost div matching textContent one could use the xpath selector instead of querySelectorAll:

```
const selector = 'div'
const text = 'One'
await page.$x("//selector[contains(text(), text)]")
```

If this change makes sense, I'd be happy to make a pull request. If not, please let me know where my assumptions are incorrect. 

Thanks for a great utility!

**Comment by neoziro** [comment]
This is a very interesting point! I don't think it is a good idea to move to xpath because selectors are not compatible. I think it is understandable for users that this is the first match that is clicked, but we should precise it in the readme.

**Comment by sethlesky** [comment]
Coming from Cypress, the behavior I would have expected would have been click the innermost div that contains the specified text (https://docs.cypress.io/api/commands/contains.html#Syntax).

For my case, the alternative would be something like the following:
```
    const divButton = (await page.$x("//div[contains(text(), 'click me div')]"))
    expect(divButton).not.toEqual([])
    if (divButton.length > 0) {
      await divButton[0].click()
    } else {
      throw new Error('click me div not found')
    }
```

I'm sure the above could be simplified further, but having a single interface with expect-puppeteer would be nicer imo.
