### ISSUE TITLE
appMode: true in jest-puppeteer.config.js results in error

### ISSUE THREAD

**Issue by sethlesky** [smooth-code/jest-puppeteer#85]
Settings appMode to true in jest-puppeteer.config.js 
```
module.exports = {
  launch: {
    headless: false,
    appMode: true,
  },
}
```

Results in the following error:
```
 FAIL  src/tests/error.test.js
  ● Test suite failed to run

    wsEndpoint not found

      at PuppeteerEnvironment.setup (node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:59:13)
```

Without appMode window area of my webapp only uses a small portion of the viewport during headful tests.

**Comment by CharlyWebsterJG** [comment]
got the same issue :(

**Comment by neoziro** [comment]
[`appMode` is not documented an experimental](https://github.com/GoogleChrome/puppeteer/pull/1954#issuecomment-365374236). Also viewport can now be controlled in Puppeteer since 1.6.1, so this issue is now solved.
