### ISSUE TITLE
Unhelpful error message running dev-server on Travis CI

### ISSUE THREAD

**Issue by ebello** [smooth-code/jest-puppeteer#89]
I'm trying to get puppeteer running with a gatsby site on Travis CI. My `jest-puppeteer.config.js` is as follows:
```
module.exports = {
  server: {
    command: './node_modules/.bin/gatsby serve',
    port: 9000,
    debug: true,
  },
  launch: {
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  },
};
```

When `jest --runInBand --ci` is run I get the following output:
```
Jest dev-server output:
7
Server has taken more than 5000ms to start.

☝️ You can set "server.launchTimeout" in jest-puppeteer.config.js
error Command failed with exit code 1.
```

I'm not sure where the error is coming from. How can I best debug this further?

**Comment by Niceplace** [comment]
`server` has a `launchTimeout` property that you can configure (in milliseconds). You could try increasing it.

If you look inside `jest-dev-server` package, inside `src/globals.js`, you can see that the default value is set to 5000ms.

```
const DEFAULT_CONFIG = {
  debug: false,
  options: {},
  launchTimeout: 5000,
  port: null,
  usedPortAction: 'ask',
}

**Comment by njbmartin** [comment]
As mentioned above, your config is missing `launchTimeout`. That's why it's defaulting to 5000ms as the error suggests.

Here's what you want:

```js
module.exports = {
  server: {
    command: './node_modules/.bin/gatsby serve',
    launchTimeout: 30000, // set to 30s
    port: 9000,
    debug: true,
  },
  launch: {
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  },
};
```


https://github.com/smooth-code/jest-puppeteer/tree/master/packages/jest-dev-server#launchtimeout

**Comment by ebello** [comment]
I appreciate the help, both of you. I extended the launch timeout to 30 seconds and that seems to have done it.
