### ISSUE TITLE
System Idle Process on Windows reports port in use (jest-dev-server)

### ISSUE THREAD

**Issue by njbmartin** [smooth-code/jest-puppeteer#91]
Found an interesting issue related to `jest-dev-server` in which the port hasn't been fully released on Windows. It can be reused, but it's attached to the "System Idle Process".

https://github.com/smooth-code/jest-puppeteer/blob/cda5a30ec24fd7ae995663aa47f5028cd1a45101/packages/jest-dev-server/src/global.js#L92

This will report **System Idle Process** as the process currently using the port. This has a process id of `0`.

Changing the proceeding line `if (portProcess) {` to `if (portProcess && portProcess.pid > 0) {` resolves the issue by asserting that it's not being held by `System Idle Process` and allows the server to be started.

**Comment by neoziro** [comment]
Good catch, can you submit a PR for it?
