### ISSUE TITLE
Add wait-port support for protocol and host [jest-dev-server]

### ISSUE THREAD

**Issue by njbmartin** [smooth-code/jest-puppeteer#92]
Discovered that `wait-port` supports checking an endpoint instead of just a port being opened, if you provide the protocol via the API.

> This is useful if the port is opened before the app is compiled. Eg. using `webpack-dev-server`:

```
i ｢wds｣: Project is running at http://localhost:4444/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to /index.html
i ｢wdm｣: wait until bundle finished: /
i ｢wdm｣: Hash: e1e9848a784224aac473
```

In my case, the compilation takes an additional 10 seconds after the port is opened.

I made a few modifications in order to support this:

```js
const DEFAULT_CONFIG = {
  debug: false,
  options: {},
  launchTimeout: 5000,
  host: null,
  port: null,
  protocol: null,
  usedPortAction: 'ask',
}

...

waitPort({
  host: config.host,
  protocol: config.protocol,
  port: config.port,
  output: 'silent',
}),
```

So then the jest-puppeteer config would potentially look like:

```js
module.exports = {
  server: {
    command: 'npm run test:start',
    debug: true,
    protocol: 'http',
    launchTimeout: 30000,
    usedPortAction: 'ignore',
    port: 4444
  }
}
```

**Comment by ollelauribostrom** [comment]
Is this published to npm yet?

**Comment by neoziro** [comment]
@ollelauribostrom yes it is.
