### ISSUE TITLE
Adding server port ask for root password

### ISSUE THREAD

**Issue by cancerberoSgx** [smooth-code/jest-puppeteer#96]
This works in my system (arch linux, node 10, latest puppeteteer, jest, etc)

```
  launch: {
    args: ['--no-sandbox'],
  },
  server: {
    command: `node dist/test-scripts/server-mocks/server1.js`,
  }
```

But if I add the port number, (high number like 3001 and not busy) then the test interrupts and the terminal ask for my root password like sudo. Is that normal? I'm not entering my root password for running a test, at all and I know in my system my user has permissions to open / close it... 

I'm able to run the command manually OK. I tried with headless: false, --disable-setuid-sandbox and 
  --usedPortAction: 'error' but with no luck,

DO you think this is a problem with sandbox ? I wanted to report this since recent security incidents in npmjs.org - sore is nothing but just in case.

Will try to reproduce the issue in jest-dev-server. Any tip / help is appreciated. Thanks - good work, keep it up

**Comment by CyrilQuandalle** [comment]
Hi,
I have the same issue, even if I change the rights on the npm root folder it is still asking me for my root password.
Is there any workaround that you have found @cancerberoSgx ?

**Comment by neoziro** [comment]
I think it is a problem in your server. You should try to run "npm start" without Jest Puppeteer and see what's going on. The requirement of a root password can be multiple things: a usage of a restricted port, the execution rights of the process...

This issue is not relative to Jest Puppeteer but I let it opened if someone want to help.

**Comment by cancerberoSgx** [comment]
@neoziro I wouldn't be so sure about "This issue is not relative to Jest Puppeteer". I use lots of different servers, using the same terminal, user, port, interface, groups, interfaces both for puppeteer and also other servers on top of jest and never had this problem. Did you tried to reproduce the issue in arch linux at least ? is as easy as providing the configuration I just did in my first comment. I had reproduce it using arch linux and manjaro linux (archlinux - based distribution). Both are very popular linux distros BTW. Will try to see if the same happens on debian or other distros but unfortunately don't have much time to invest on this. Thanks.

**Comment by CyrilQuandalle** [comment]
Thank you for your answer @cancerberoSgx ;-)
I ended up using npm-run-all to run my tasks in parallele:  starting the server and running the tests with race condition options to kill the server at the end of the tests ;-)

**Comment by BenoitZugmeyer** [comment]
I have the same issue. This is because `jest-dev-server` is using `find-process` to find the process with a given port, and `find-process` is [using the command `sudo netstat -tunlp`](https://github.com/yibn2008/find-process/blob/c12511dd908cafbd00d8fb6d55fd5d7af312437f/lib/find_pid.js#L54-L58).

This is really unfortunate, this project seemed nice but I really can't enter my root password every time I need to run tests. I guess setting `config.usedPortAction = 'ignore'` should not run `find-process` at all, so no `sudo` would be needed.

**Comment by neoziro** [comment]
@BenoitZugmeyer good catch thanks, so it is actually a bug.

**Comment by rs-8** [comment]
I have the same. config.usedPortAction = 'ignore' this doesnt work for me. So how can i fix that?

**Comment by cancerberoSgx** [comment]
Any news on this ? Why is it jest-puppeteer scanning my processes ? IMO, As the user I expect to be responsible of providing the port number, if it's busy is my problem. This tool should just open the server on that port and that's it. Thanks.

**Comment by yaniv-li** [comment]
I workaround (hack) would be to put
`global.process.getuid = () => 0;`
at the top of the jest-puppeteer.config.js file before module.export
if it has no implications for your tests.
If it has just copy the function before `global.process._getuid = global.process.getuid;`
and resign it after the server starts at the beginning of your test.

**Comment by neoziro** [comment]
I think it is not possible to test if port is used without sudo. In fact it is because I had never experienced this issue on Mac.

Anyway I can't do anything for it, you should investigate in `find-process` package and try to patch it to avoid this.

**Comment by mzedeler** [comment]
If `usedPortAction` is set to `error`, it won't ever be required to get the process id of the listening process.

**Comment by neoziro** [comment]
Yes you are right, could you submit a fix?

**Comment by mzedeler** [comment]
Ok. I'm on it :-)

**Comment by mzedeler** [comment]
@neoziro - I suppose the fix goes into jest-dev-server, not jest-puppeteer.

**Comment by neoziro** [comment]
Of course 😉, but it is in the same repo.

**Comment by mzedeler** [comment]
https://github.com/smooth-code/jest-puppeteer/pull/149

I haven't had time to test it yet, but I'd like to know if this is the right direction, I'm taking.
