### ISSUE TITLE
Race Condition on setting WSendpoint

### ISSUE THREAD

**Issue by OGEDENSE** [smooth-code/jest-puppeteer#98]
When using multiple instances of Jest they will each launch their own browser, but as soon as the setup starts they will connect to the wrong browser. I.e 6 instances will spawn 6 browsers, but only connect to 1 - 2 of them. I suspect this is because when the WSendpoint is written to the tmp directory, all the instances are reading to and writing to this same file concurrently. 

In addition, adding a configuration option for the preset that will force the jest instances to either share a browser or use their own browser and changing how WSendpoint is saved accordingly would solve this issue and be a useful feature.

I tinkered around with preset on my own and was able to force them to use the same browser but I have yet to force them to use distinct browsers.

**Comment by srounce** [comment]
Prepending the PID of the 'root' Jest process seems to work well for preventing them clobbering each other.

**Comment by neoziro** [comment]
Fixed in #103
